package com.softcat.weatherapp.jsonMocks

val weatherHistoryJson = """
    {
        "location": {
            "name": "London",
            "region": "City of London, Greater London",
            "country": "United Kingdom",
            "lat": 51.5171,
            "lon": -0.1062,
            "tz_id": "Europe/London",
            "localtime_epoch": 1742922048,
            "localtime": "2025-03-25 17:00"
        },
        "forecast": {
            "forecastday": [
                {
                    "lastUpdated": "2025-03-20",
                    "date_epoch": 1742428800,
                    "day": {
                        "maxtemp_c": 17.9,
                        "maxtemp_f": 64.2,
                        "mintemp_c": 7.2,
                        "mintemp_f": 45.0,
                        "avgtemp_c": 12.1,
                        "avgtemp_f": 53.8,
                        "maxwind_mph": 8.9,
                        "maxwind_kph": 14.4,
                        "totalprecip_mm": 0.0,
                        "totalprecip_in": 0.0,
                        "totalsnow_cm": 0.0,
                        "avgvis_km": 10.0,
                        "avgvis_miles": 6.0,
                        "avghumidity": 72,
                        "daily_will_it_rain": 0,
                        "daily_chance_of_rain": 0,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Overcast",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            "code": 1009
                        },
                        "uv": 4.0
                    },
                    "astro": {
                        "sunrise": "06:03 AM",
                        "sunset": "06:14 PM",
                        "moonrise": "12:32 AM",
                        "moonset": "07:46 AM",
                        "moon_phase": "Waning Gibbous",
                        "moon_illumination": 73
                    },
                    "hour": [
                        {
                            "time_epoch": 1742428800,
                            "time": "2025-03-20 00:00",
                            "temp_c": 9.9,
                            "temp_f": 49.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 1.8,
                            "wind_kph": 2.9,
                            "wind_degree": 159,
                            "wind_dir": "SSE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.19,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 73,
                            "cloud": 58,
                            "feelslike_c": 9.9,
                            "feelslike_f": 49.9,
                            "windchill_c": 9.9,
                            "windchill_f": 49.9,
                            "heatindex_c": 9.9,
                            "heatindex_f": 49.9,
                            "dewpoint_c": 5.4,
                            "dewpoint_f": 41.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 3.1,
                            "gust_kph": 5.0,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742432400,
                            "time": "2025-03-20 01:00",
                            "temp_c": 9.8,
                            "temp_f": 49.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 2.2,
                            "wind_kph": 3.6,
                            "wind_degree": 130,
                            "wind_dir": "SE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.19,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 74,
                            "cloud": 37,
                            "feelslike_c": 10.1,
                            "feelslike_f": 50.1,
                            "windchill_c": 10.1,
                            "windchill_f": 50.1,
                            "heatindex_c": 9.8,
                            "heatindex_f": 49.7,
                            "dewpoint_c": 5.4,
                            "dewpoint_f": 41.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 4.0,
                            "gust_kph": 6.5,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742436000,
                            "time": "2025-03-20 02:00",
                            "temp_c": 9.8,
                            "temp_f": 49.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 2.2,
                            "wind_kph": 3.6,
                            "wind_degree": 132,
                            "wind_dir": "SE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.18,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 75,
                            "cloud": 47,
                            "feelslike_c": 10.0,
                            "feelslike_f": 49.9,
                            "windchill_c": 10.0,
                            "windchill_f": 49.9,
                            "heatindex_c": 9.8,
                            "heatindex_f": 49.6,
                            "dewpoint_c": 5.5,
                            "dewpoint_f": 42.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 4.0,
                            "gust_kph": 6.4,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742439600,
                            "time": "2025-03-20 03:00",
                            "temp_c": 9.6,
                            "temp_f": 49.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 1.8,
                            "wind_kph": 2.9,
                            "wind_degree": 162,
                            "wind_dir": "SSE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.17,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 76,
                            "cloud": 52,
                            "feelslike_c": 9.6,
                            "feelslike_f": 49.4,
                            "windchill_c": 9.6,
                            "windchill_f": 49.4,
                            "heatindex_c": 9.6,
                            "heatindex_f": 49.4,
                            "dewpoint_c": 5.7,
                            "dewpoint_f": 42.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 3.2,
                            "gust_kph": 5.1,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742443200,
                            "time": "2025-03-20 04:00",
                            "temp_c": 8.2,
                            "temp_f": 46.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 0.9,
                            "wind_kph": 1.4,
                            "wind_degree": 179,
                            "wind_dir": "S",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.17,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 78,
                            "cloud": 34,
                            "feelslike_c": 8.2,
                            "feelslike_f": 46.7,
                            "windchill_c": 8.2,
                            "windchill_f": 46.7,
                            "heatindex_c": 8.2,
                            "heatindex_f": 46.7,
                            "dewpoint_c": 5.6,
                            "dewpoint_f": 42.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 1.6,
                            "gust_kph": 2.6,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742446800,
                            "time": "2025-03-20 05:00",
                            "temp_c": 7.9,
                            "temp_f": 46.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 1.6,
                            "wind_kph": 2.5,
                            "wind_degree": 173,
                            "wind_dir": "S",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.17,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 80,
                            "cloud": 35,
                            "feelslike_c": 7.9,
                            "feelslike_f": 46.2,
                            "windchill_c": 7.9,
                            "windchill_f": 46.2,
                            "heatindex_c": 7.9,
                            "heatindex_f": 46.2,
                            "dewpoint_c": 5.6,
                            "dewpoint_f": 42.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 2.8,
                            "gust_kph": 4.6,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742450400,
                            "time": "2025-03-20 06:00",
                            "temp_c": 7.2,
                            "temp_f": 45.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                "code": 1006
                            },
                            "wind_mph": 1.6,
                            "wind_kph": 2.5,
                            "wind_degree": 156,
                            "wind_dir": "SSE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.17,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 82,
                            "cloud": 70,
                            "feelslike_c": 7.2,
                            "feelslike_f": 45.0,
                            "windchill_c": 7.2,
                            "windchill_f": 45.0,
                            "heatindex_c": 7.2,
                            "heatindex_f": 45.0,
                            "dewpoint_c": 5.4,
                            "dewpoint_f": 41.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 3.0,
                            "gust_kph": 4.8,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742454000,
                            "time": "2025-03-20 07:00",
                            "temp_c": 8.0,
                            "temp_f": 46.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 2.0,
                            "wind_kph": 3.2,
                            "wind_degree": 132,
                            "wind_dir": "SE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.18,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 81,
                            "cloud": 100,
                            "feelslike_c": 8.2,
                            "feelslike_f": 46.8,
                            "windchill_c": 8.2,
                            "windchill_f": 46.8,
                            "heatindex_c": 8.0,
                            "heatindex_f": 46.4,
                            "dewpoint_c": 5.7,
                            "dewpoint_f": 42.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 3.6,
                            "gust_kph": 5.8,
                            "uv": 2.0
                        },
                        {
                            "time_epoch": 1742457600,
                            "time": "2025-03-20 08:00",
                            "temp_c": 10.0,
                            "temp_f": 50.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 2.7,
                            "wind_kph": 4.3,
                            "wind_degree": 122,
                            "wind_dir": "ESE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.19,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 79,
                            "cloud": 98,
                            "feelslike_c": 10.0,
                            "feelslike_f": 50.0,
                            "windchill_c": 10.0,
                            "windchill_f": 50.0,
                            "heatindex_c": 10.0,
                            "heatindex_f": 50.0,
                            "dewpoint_c": 6.5,
                            "dewpoint_f": 43.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 6.6,
                            "gust_kph": 10.7,
                            "uv": 3.0
                        },
                        {
                            "time_epoch": 1742461200,
                            "time": "2025-03-20 09:00",
                            "temp_c": 10.2,
                            "temp_f": 50.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 3.1,
                            "wind_kph": 5.0,
                            "wind_degree": 128,
                            "wind_dir": "SE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.19,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 81,
                            "cloud": 100,
                            "feelslike_c": 9.9,
                            "feelslike_f": 49.9,
                            "windchill_c": 9.9,
                            "windchill_f": 49.9,
                            "heatindex_c": 10.2,
                            "heatindex_f": 50.3,
                            "dewpoint_c": 7.1,
                            "dewpoint_f": 44.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 5.1,
                            "gust_kph": 8.2,
                            "uv": 3.0
                        },
                        {
                            "time_epoch": 1742464800,
                            "time": "2025-03-20 10:00",
                            "temp_c": 12.2,
                            "temp_f": 54.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 3.4,
                            "wind_kph": 5.4,
                            "wind_degree": 137,
                            "wind_dir": "SE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.19,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 82,
                            "cloud": 100,
                            "feelslike_c": 12.2,
                            "feelslike_f": 54.0,
                            "windchill_c": 12.2,
                            "windchill_f": 54.0,
                            "heatindex_c": 12.2,
                            "heatindex_f": 54.0,
                            "dewpoint_c": 7.7,
                            "dewpoint_f": 45.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 5.2,
                            "gust_kph": 8.3,
                            "uv": 3.0
                        },
                        {
                            "time_epoch": 1742468400,
                            "time": "2025-03-20 11:00",
                            "temp_c": 13.9,
                            "temp_f": 56.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 4.3,
                            "wind_kph": 6.8,
                            "wind_degree": 141,
                            "wind_dir": "SE",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.18,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 75,
                            "cloud": 41,
                            "feelslike_c": 13.7,
                            "feelslike_f": 56.7,
                            "windchill_c": 13.7,
                            "windchill_f": 56.7,
                            "heatindex_c": 13.9,
                            "heatindex_f": 56.9,
                            "dewpoint_c": 7.9,
                            "dewpoint_f": 46.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 5.7,
                            "gust_kph": 9.2,
                            "uv": 4.0
                        },
                        {
                            "time_epoch": 1742472000,
                            "time": "2025-03-20 12:00",
                            "temp_c": 15.8,
                            "temp_f": 60.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 4.7,
                            "wind_kph": 7.6,
                            "wind_degree": 135,
                            "wind_dir": "SE",
                            "pressure_mb": 1021.0,
                            "pressure_in": 30.16,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 64,
                            "cloud": 19,
                            "feelslike_c": 15.8,
                            "feelslike_f": 60.4,
                            "windchill_c": 15.8,
                            "windchill_f": 60.4,
                            "heatindex_c": 15.8,
                            "heatindex_f": 60.4,
                            "dewpoint_c": 7.8,
                            "dewpoint_f": 46.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.3,
                            "gust_kph": 13.4,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1742475600,
                            "time": "2025-03-20 13:00",
                            "temp_c": 17.6,
                            "temp_f": 63.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 5.4,
                            "wind_kph": 8.6,
                            "wind_degree": 133,
                            "wind_dir": "SE",
                            "pressure_mb": 1021.0,
                            "pressure_in": 30.14,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 56,
                            "cloud": 58,
                            "feelslike_c": 17.6,
                            "feelslike_f": 63.7,
                            "windchill_c": 17.6,
                            "windchill_f": 63.7,
                            "heatindex_c": 17.6,
                            "heatindex_f": 63.7,
                            "dewpoint_c": 6.8,
                            "dewpoint_f": 44.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.5,
                            "gust_kph": 16.8,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1742479200,
                            "time": "2025-03-20 14:00",
                            "temp_c": 17.9,
                            "temp_f": 64.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 7.2,
                            "wind_kph": 11.5,
                            "wind_degree": 138,
                            "wind_dir": "SE",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.12,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 53,
                            "cloud": 59,
                            "feelslike_c": 17.9,
                            "feelslike_f": 64.2,
                            "windchill_c": 17.9,
                            "windchill_f": 64.2,
                            "heatindex_c": 17.9,
                            "heatindex_f": 64.2,
                            "dewpoint_c": 6.8,
                            "dewpoint_f": 44.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.6,
                            "gust_kph": 18.7,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1742482800,
                            "time": "2025-03-20 15:00",
                            "temp_c": 17.6,
                            "temp_f": 63.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 8.7,
                            "wind_kph": 14.0,
                            "wind_degree": 144,
                            "wind_dir": "SE",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.11,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 54,
                            "cloud": 55,
                            "feelslike_c": 17.6,
                            "feelslike_f": 63.7,
                            "windchill_c": 17.6,
                            "windchill_f": 63.7,
                            "heatindex_c": 17.6,
                            "heatindex_f": 63.7,
                            "dewpoint_c": 6.8,
                            "dewpoint_f": 44.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.5,
                            "gust_kph": 16.8,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1742486400,
                            "time": "2025-03-20 16:00",
                            "temp_c": 17.2,
                            "temp_f": 63.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Cloudy",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                                "code": 1006
                            },
                            "wind_mph": 8.9,
                            "wind_kph": 14.4,
                            "wind_degree": 140,
                            "wind_dir": "SE",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.11,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 55,
                            "cloud": 70,
                            "feelslike_c": 17.2,
                            "feelslike_f": 63.0,
                            "windchill_c": 17.2,
                            "windchill_f": 63.0,
                            "heatindex_c": 17.2,
                            "heatindex_f": 63.0,
                            "dewpoint_c": 6.8,
                            "dewpoint_f": 44.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.4,
                            "gust_kph": 18.3,
                            "uv": 4.0
                        },
                        {
                            "time_epoch": 1742490000,
                            "time": "2025-03-20 17:00",
                            "temp_c": 16.2,
                            "temp_f": 61.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.6,
                            "wind_kph": 12.2,
                            "wind_degree": 131,
                            "wind_dir": "SE",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.1,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 60,
                            "cloud": 12,
                            "feelslike_c": 16.2,
                            "feelslike_f": 61.1,
                            "windchill_c": 16.2,
                            "windchill_f": 61.1,
                            "heatindex_c": 16.2,
                            "heatindex_f": 61.1,
                            "dewpoint_c": 7.0,
                            "dewpoint_f": 44.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.2,
                            "gust_kph": 21.2,
                            "uv": 5.0
                        },
                        {
                            "time_epoch": 1742493600,
                            "time": "2025-03-20 18:00",
                            "temp_c": 14.7,
                            "temp_f": 58.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Sunny",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.3,
                            "wind_kph": 10.1,
                            "wind_degree": 117,
                            "wind_dir": "ESE",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 68,
                            "cloud": 6,
                            "feelslike_c": 14.3,
                            "feelslike_f": 57.7,
                            "windchill_c": 14.3,
                            "windchill_f": 57.7,
                            "heatindex_c": 14.7,
                            "heatindex_f": 58.5,
                            "dewpoint_c": 7.4,
                            "dewpoint_f": 45.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.7,
                            "gust_kph": 15.7,
                            "uv": 4.0
                        },
                        {
                            "time_epoch": 1742497200,
                            "time": "2025-03-20 19:00",
                            "temp_c": 13.4,
                            "temp_f": 56.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.3,
                            "wind_kph": 10.1,
                            "wind_degree": 118,
                            "wind_dir": "ESE",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.1,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 73,
                            "cloud": 15,
                            "feelslike_c": 12.7,
                            "feelslike_f": 54.8,
                            "windchill_c": 12.7,
                            "windchill_f": 54.8,
                            "heatindex_c": 13.4,
                            "heatindex_f": 56.1,
                            "dewpoint_c": 7.6,
                            "dewpoint_f": 45.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.5,
                            "gust_kph": 16.9,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742500800,
                            "time": "2025-03-20 20:00",
                            "temp_c": 11.6,
                            "temp_f": 52.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 99,
                            "wind_dir": "E",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 76,
                            "cloud": 9,
                            "feelslike_c": 10.4,
                            "feelslike_f": 50.6,
                            "windchill_c": 10.4,
                            "windchill_f": 50.6,
                            "heatindex_c": 11.6,
                            "heatindex_f": 52.9,
                            "dewpoint_c": 7.5,
                            "dewpoint_f": 45.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.6,
                            "gust_kph": 18.7,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742504400,
                            "time": "2025-03-20 21:00",
                            "temp_c": 11.1,
                            "temp_f": 52.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 99,
                            "wind_dir": "E",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.08,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 77,
                            "cloud": 3,
                            "feelslike_c": 9.8,
                            "feelslike_f": 49.6,
                            "windchill_c": 9.8,
                            "windchill_f": 49.6,
                            "heatindex_c": 11.1,
                            "heatindex_f": 52.0,
                            "dewpoint_c": 7.2,
                            "dewpoint_f": 45.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.8,
                            "gust_kph": 19.0,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742508000,
                            "time": "2025-03-20 22:00",
                            "temp_c": 10.7,
                            "temp_f": 51.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 103,
                            "wind_dir": "ESE",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.07,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 78,
                            "cloud": 2,
                            "feelslike_c": 9.3,
                            "feelslike_f": 48.7,
                            "windchill_c": 9.3,
                            "windchill_f": 48.7,
                            "heatindex_c": 10.7,
                            "heatindex_f": 51.2,
                            "dewpoint_c": 7.0,
                            "dewpoint_f": 44.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.2,
                            "gust_kph": 19.7,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742511600,
                            "time": "2025-03-20 23:00",
                            "temp_c": 10.2,
                            "temp_f": 50.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.0,
                            "wind_kph": 9.7,
                            "wind_degree": 104,
                            "wind_dir": "ESE",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.06,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 79,
                            "cloud": 2,
                            "feelslike_c": 8.9,
                            "feelslike_f": 48.0,
                            "windchill_c": 8.9,
                            "windchill_f": 48.0,
                            "heatindex_c": 10.2,
                            "heatindex_f": 50.3,
                            "dewpoint_c": 6.8,
                            "dewpoint_f": 44.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.2,
                            "gust_kph": 18.0,
                            "uv": 0.0
                        }
                    ]
                }
            ]
        }
    }
""".trimIndent()