package com.softcat.weatherapp.jsonMocks

val weatherForecastJson = """
    {
        "location": {
            "name": "Moscow",
            "region": "Moscow City",
            "country": "Russia",
            "lat": 55.7522,
            "lon": 37.6156,
            "tz_id": "Europe/Moscow",
            "localtime_epoch": 1742922674,
            "localtime": "2025-03-25 20:11"
        },
        "current": {
            "last_updated_epoch": 1742922000,
            "last_updated": "2025-03-25 20:00",
            "temp_c": 2.3,
            "temp_f": 36.1,
            "is_day": 0,
            "condition": {
                "text": "Light rain",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                "code": 1183
            },
            "wind_mph": 7.8,
            "wind_kph": 12.6,
            "wind_degree": 166,
            "wind_dir": "SSE",
            "pressure_mb": 1016.0,
            "pressure_in": 30.0,
            "precip_mm": 0.01,
            "precip_in": 0.0,
            "humidity": 93,
            "cloud": 100,
            "feelslike_c": -1.1,
            "feelslike_f": 29.9,
            "windchill_c": -1.1,
            "windchill_f": 30.0,
            "heatindex_c": 2.3,
            "heatindex_f": 36.1,
            "dewpoint_c": 1.8,
            "dewpoint_f": 35.2,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "uv": 0.0,
            "gust_mph": 11.1,
            "gust_kph": 17.8
        },
        "forecast": {
            "forecastday": [
                {
                    "lastUpdated": "2025-03-25",
                    "date_epoch": 1742860800,
                    "day": {
                        "maxtemp_c": 4.1,
                        "maxtemp_f": 39.3,
                        "mintemp_c": 2.0,
                        "mintemp_f": 35.6,
                        "avgtemp_c": 3.6,
                        "avgtemp_f": 38.6,
                        "maxwind_mph": 13.9,
                        "maxwind_kph": 22.3,
                        "totalprecip_mm": 2.04,
                        "totalprecip_in": 0.08,
                        "totalsnow_cm": 0.01,
                        "avgvis_km": 7.7,
                        "avgvis_miles": 4.0,
                        "avghumidity": 91,
                        "daily_will_it_rain": 1,
                        "daily_chance_of_rain": 95,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "uv": 0.1
                    },
                    "astro": {
                        "sunrise": "06:18 AM",
                        "sunset": "06:54 PM",
                        "moonrise": "05:30 AM",
                        "moonset": "12:51 PM",
                        "moon_phase": "Waning Crescent",
                        "moon_illumination": 25,
                        "is_moon_up": 0,
                        "is_sun_up": 0
                    },
                    "hour": [
                        {
                            "time_epoch": 1742850000,
                            "time": "2025-03-25 00:00",
                            "temp_c": 4.9,
                            "temp_f": 40.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                "code": 1006
                            },
                            "wind_mph": 11.6,
                            "wind_kph": 18.7,
                            "wind_degree": 168,
                            "wind_dir": "SSE",
                            "pressure_mb": 1024.0,
                            "pressure_in": 30.24,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 71,
                            "cloud": 75,
                            "feelslike_c": 1.1,
                            "feelslike_f": 33.9,
                            "windchill_c": 1.1,
                            "windchill_f": 33.9,
                            "heatindex_c": 4.9,
                            "heatindex_f": 40.8,
                            "dewpoint_c": 0.2,
                            "dewpoint_f": 32.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 19.1,
                            "gust_kph": 30.7,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742853600,
                            "time": "2025-03-25 01:00",
                            "temp_c": 5.0,
                            "temp_f": 41.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 11.6,
                            "wind_kph": 18.7,
                            "wind_degree": 175,
                            "wind_dir": "S",
                            "pressure_mb": 1024.0,
                            "pressure_in": 30.23,
                            "precip_mm": 0.01,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 69,
                            "cloud": 90,
                            "feelslike_c": 1.2,
                            "feelslike_f": 34.2,
                            "windchill_c": 1.2,
                            "windchill_f": 34.2,
                            "heatindex_c": 5.0,
                            "heatindex_f": 41.0,
                            "dewpoint_c": -0.2,
                            "dewpoint_f": 31.7,
                            "will_it_rain": 1,
                            "chance_of_rain": 74,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 18.7,
                            "gust_kph": 30.2,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742857200,
                            "time": "2025-03-25 02:00",
                            "temp_c": 4.9,
                            "temp_f": 40.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/266.png",
                                "code": 1153
                            },
                            "wind_mph": 13.0,
                            "wind_kph": 20.9,
                            "wind_degree": 179,
                            "wind_dir": "S",
                            "pressure_mb": 1023.0,
                            "pressure_in": 30.21,
                            "precip_mm": 0.21,
                            "precip_in": 0.01,
                            "snow_cm": 0.0,
                            "humidity": 75,
                            "cloud": 100,
                            "feelslike_c": 0.8,
                            "feelslike_f": 33.4,
                            "windchill_c": 0.8,
                            "windchill_f": 33.4,
                            "heatindex_c": 4.9,
                            "heatindex_f": 40.8,
                            "dewpoint_c": 0.7,
                            "dewpoint_f": 33.3,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 19.6,
                            "gust_kph": 31.5,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742860800,
                            "time": "2025-03-25 03:00",
                            "temp_c": 4.6,
                            "temp_f": 40.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 13.9,
                            "wind_kph": 22.3,
                            "wind_degree": 175,
                            "wind_dir": "S",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.19,
                            "precip_mm": 0.01,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 81,
                            "cloud": 100,
                            "feelslike_c": 0.3,
                            "feelslike_f": 32.5,
                            "windchill_c": 0.3,
                            "windchill_f": 32.5,
                            "heatindex_c": 4.6,
                            "heatindex_f": 40.2,
                            "dewpoint_c": 1.6,
                            "dewpoint_f": 34.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 76,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 20.4,
                            "gust_kph": 32.8,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742864400,
                            "time": "2025-03-25 04:00",
                            "temp_c": 4.4,
                            "temp_f": 39.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 13.9,
                            "wind_kph": 22.3,
                            "wind_degree": 174,
                            "wind_dir": "S",
                            "pressure_mb": 1022.0,
                            "pressure_in": 30.17,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 84,
                            "cloud": 100,
                            "feelslike_c": 0.0,
                            "feelslike_f": 32.1,
                            "windchill_c": 0.0,
                            "windchill_f": 32.1,
                            "heatindex_c": 4.4,
                            "heatindex_f": 39.9,
                            "dewpoint_c": 1.9,
                            "dewpoint_f": 35.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 20.2,
                            "gust_kph": 32.5,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742868000,
                            "time": "2025-03-25 05:00",
                            "temp_c": 4.2,
                            "temp_f": 39.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 13.6,
                            "wind_kph": 22.0,
                            "wind_degree": 177,
                            "wind_dir": "S",
                            "pressure_mb": 1021.0,
                            "pressure_in": 30.16,
                            "precip_mm": 0.01,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 87,
                            "cloud": 100,
                            "feelslike_c": -0.2,
                            "feelslike_f": 31.7,
                            "windchill_c": -0.2,
                            "windchill_f": 31.7,
                            "heatindex_c": 4.2,
                            "heatindex_f": 39.6,
                            "dewpoint_c": 2.2,
                            "dewpoint_f": 36.0,
                            "will_it_rain": 1,
                            "chance_of_rain": 78,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 19.7,
                            "gust_kph": 31.6,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742871600,
                            "time": "2025-03-25 06:00",
                            "temp_c": 3.9,
                            "temp_f": 39.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 13.2,
                            "wind_kph": 21.2,
                            "wind_degree": 177,
                            "wind_dir": "S",
                            "pressure_mb": 1021.0,
                            "pressure_in": 30.15,
                            "precip_mm": 0.04,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 94,
                            "cloud": 100,
                            "feelslike_c": -0.5,
                            "feelslike_f": 31.1,
                            "windchill_c": -0.5,
                            "windchill_f": 31.1,
                            "heatindex_c": 3.9,
                            "heatindex_f": 39.0,
                            "dewpoint_c": 3.0,
                            "dewpoint_f": 37.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 68,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 19.2,
                            "gust_kph": 31.0,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742875200,
                            "time": "2025-03-25 07:00",
                            "temp_c": 3.9,
                            "temp_f": 39.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 13.0,
                            "wind_kph": 20.9,
                            "wind_degree": 179,
                            "wind_dir": "S",
                            "pressure_mb": 1021.0,
                            "pressure_in": 30.14,
                            "precip_mm": 0.02,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -0.4,
                            "feelslike_f": 31.3,
                            "windchill_c": -0.4,
                            "windchill_f": 31.3,
                            "heatindex_c": 3.9,
                            "heatindex_f": 39.1,
                            "dewpoint_c": 3.3,
                            "dewpoint_f": 37.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 77,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 18.9,
                            "gust_kph": 30.4,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742878800,
                            "time": "2025-03-25 08:00",
                            "temp_c": 3.9,
                            "temp_f": 39.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 12.8,
                            "wind_kph": 20.5,
                            "wind_degree": 177,
                            "wind_dir": "S",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.12,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -0.3,
                            "feelslike_f": 31.4,
                            "windchill_c": -0.3,
                            "windchill_f": 31.4,
                            "heatindex_c": 3.9,
                            "heatindex_f": 39.1,
                            "dewpoint_c": 3.3,
                            "dewpoint_f": 38.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 18.7,
                            "gust_kph": 30.0,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742882400,
                            "time": "2025-03-25 09:00",
                            "temp_c": 4.0,
                            "temp_f": 39.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 12.3,
                            "wind_kph": 19.8,
                            "wind_degree": 179,
                            "wind_dir": "S",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.12,
                            "precip_mm": 0.01,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -0.2,
                            "feelslike_f": 31.6,
                            "windchill_c": -0.2,
                            "windchill_f": 31.6,
                            "heatindex_c": 4.0,
                            "heatindex_f": 39.1,
                            "dewpoint_c": 3.3,
                            "dewpoint_f": 38.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 66,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.9,
                            "gust_kph": 28.9,
                            "uv": 0.1
                        },
                        {
                            "time_epoch": 1742886000,
                            "time": "2025-03-25 10:00",
                            "temp_c": 3.9,
                            "temp_f": 39.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 12.1,
                            "wind_kph": 19.4,
                            "wind_degree": 179,
                            "wind_dir": "S",
                            "pressure_mb": 1020.0,
                            "pressure_in": 30.11,
                            "precip_mm": 0.1,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -0.3,
                            "feelslike_f": 31.5,
                            "windchill_c": -0.3,
                            "windchill_f": 31.5,
                            "heatindex_c": 3.9,
                            "heatindex_f": 39.0,
                            "dewpoint_c": 3.3,
                            "dewpoint_f": 37.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.5,
                            "gust_kph": 28.1,
                            "uv": 0.1
                        },
                        {
                            "time_epoch": 1742889600,
                            "time": "2025-03-25 11:00",
                            "temp_c": 3.8,
                            "temp_f": 38.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                                "code": 1153
                            },
                            "wind_mph": 11.2,
                            "wind_kph": 18.0,
                            "wind_degree": 179,
                            "wind_dir": "S",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.1,
                            "precip_mm": 0.31,
                            "precip_in": 0.01,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -0.2,
                            "feelslike_f": 31.6,
                            "windchill_c": -0.2,
                            "windchill_f": 31.6,
                            "heatindex_c": 3.8,
                            "heatindex_f": 38.8,
                            "dewpoint_c": 3.2,
                            "dewpoint_f": 37.7,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 16.5,
                            "gust_kph": 26.6,
                            "uv": 0.2
                        },
                        {
                            "time_epoch": 1742893200,
                            "time": "2025-03-25 12:00",
                            "temp_c": 4.0,
                            "temp_f": 39.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                                "code": 1153
                            },
                            "wind_mph": 10.7,
                            "wind_kph": 17.3,
                            "wind_degree": 177,
                            "wind_dir": "S",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.16,
                            "precip_in": 0.01,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": 0.1,
                            "feelslike_f": 32.2,
                            "windchill_c": 0.1,
                            "windchill_f": 32.2,
                            "heatindex_c": 4.0,
                            "heatindex_f": 39.1,
                            "dewpoint_c": 3.4,
                            "dewpoint_f": 38.1,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 15.8,
                            "gust_kph": 25.4,
                            "uv": 0.2
                        },
                        {
                            "time_epoch": 1742896800,
                            "time": "2025-03-25 13:00",
                            "temp_c": 4.1,
                            "temp_f": 39.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                                "code": 1153
                            },
                            "wind_mph": 10.7,
                            "wind_kph": 17.3,
                            "wind_degree": 174,
                            "wind_dir": "S",
                            "pressure_mb": 1019.0,
                            "pressure_in": 30.09,
                            "precip_mm": 0.31,
                            "precip_in": 0.01,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": 0.3,
                            "feelslike_f": 32.5,
                            "windchill_c": 0.3,
                            "windchill_f": 32.5,
                            "heatindex_c": 4.1,
                            "heatindex_f": 39.3,
                            "dewpoint_c": 3.5,
                            "dewpoint_f": 38.3,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 15.6,
                            "gust_kph": 25.2,
                            "uv": 0.2
                        },
                        {
                            "time_epoch": 1742900400,
                            "time": "2025-03-25 14:00",
                            "temp_c": 3.9,
                            "temp_f": 39.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                                "code": 1153
                            },
                            "wind_mph": 10.5,
                            "wind_kph": 16.9,
                            "wind_degree": 171,
                            "wind_dir": "S",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.07,
                            "precip_mm": 0.22,
                            "precip_in": 0.01,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": 0.1,
                            "feelslike_f": 32.1,
                            "windchill_c": 0.1,
                            "windchill_f": 32.1,
                            "heatindex_c": 3.9,
                            "heatindex_f": 39.0,
                            "dewpoint_c": 3.3,
                            "dewpoint_f": 37.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 15.3,
                            "gust_kph": 24.7,
                            "uv": 0.2
                        },
                        {
                            "time_epoch": 1742904000,
                            "time": "2025-03-25 15:00",
                            "temp_c": 3.8,
                            "temp_f": 38.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                                "code": 1153
                            },
                            "wind_mph": 11.0,
                            "wind_kph": 17.6,
                            "wind_degree": 174,
                            "wind_dir": "S",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.07,
                            "precip_mm": 0.22,
                            "precip_in": 0.01,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -0.2,
                            "feelslike_f": 31.7,
                            "windchill_c": -0.2,
                            "windchill_f": 31.7,
                            "heatindex_c": 3.8,
                            "heatindex_f": 38.8,
                            "dewpoint_c": 3.2,
                            "dewpoint_f": 37.7,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 16.0,
                            "gust_kph": 25.8,
                            "uv": 0.2
                        },
                        {
                            "time_epoch": 1742907600,
                            "time": "2025-03-25 16:00",
                            "temp_c": 3.6,
                            "temp_f": 38.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Light drizzle",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/266.png",
                                "code": 1153
                            },
                            "wind_mph": 10.3,
                            "wind_kph": 16.6,
                            "wind_degree": 172,
                            "wind_dir": "S",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.06,
                            "precip_mm": 0.18,
                            "precip_in": 0.01,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -0.2,
                            "feelslike_f": 31.6,
                            "windchill_c": -0.2,
                            "windchill_f": 31.6,
                            "heatindex_c": 3.6,
                            "heatindex_f": 38.5,
                            "dewpoint_c": 3.0,
                            "dewpoint_f": 37.4,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 15.0,
                            "gust_kph": 24.1,
                            "uv": 0.1
                        },
                        {
                            "time_epoch": 1742911200,
                            "time": "2025-03-25 17:00",
                            "temp_c": 3.2,
                            "temp_f": 37.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 9.8,
                            "wind_kph": 15.8,
                            "wind_degree": 170,
                            "wind_dir": "S",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.05,
                            "precip_mm": 0.07,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -0.6,
                            "feelslike_f": 31.0,
                            "windchill_c": -0.6,
                            "windchill_f": 31.0,
                            "heatindex_c": 3.3,
                            "heatindex_f": 37.9,
                            "dewpoint_c": 2.6,
                            "dewpoint_f": 36.8,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 14.4,
                            "gust_kph": 23.2,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742914800,
                            "time": "2025-03-25 18:00",
                            "temp_c": 2.8,
                            "temp_f": 37.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 10.3,
                            "wind_kph": 16.6,
                            "wind_degree": 168,
                            "wind_dir": "SSE",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.05,
                            "precip_mm": 0.06,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -1.2,
                            "feelslike_f": 29.8,
                            "windchill_c": -1.2,
                            "windchill_f": 29.8,
                            "heatindex_c": 2.8,
                            "heatindex_f": 37.1,
                            "dewpoint_c": 2.2,
                            "dewpoint_f": 35.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 14.8,
                            "gust_kph": 23.8,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742918400,
                            "time": "2025-03-25 19:00",
                            "temp_c": 2.4,
                            "temp_f": 36.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 9.6,
                            "wind_kph": 15.5,
                            "wind_degree": 169,
                            "wind_dir": "S",
                            "pressure_mb": 1018.0,
                            "pressure_in": 30.05,
                            "precip_mm": 0.04,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -1.6,
                            "feelslike_f": 29.1,
                            "windchill_c": -1.6,
                            "windchill_f": 29.1,
                            "heatindex_c": 2.4,
                            "heatindex_f": 36.2,
                            "dewpoint_c": 1.7,
                            "dewpoint_f": 35.0,
                            "will_it_rain": 0,
                            "chance_of_rain": 67,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.8,
                            "gust_kph": 22.2,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742922000,
                            "time": "2025-03-25 20:00",
                            "temp_c": 2.3,
                            "temp_f": 36.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Light rain",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/296.png",
                                "code": 1183
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 166,
                            "wind_dir": "SSE",
                            "pressure_mb": 1016.0,
                            "pressure_in": 30.0,
                            "precip_mm": 0.01,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 93,
                            "cloud": 100,
                            "feelslike_c": -1.1,
                            "feelslike_f": 30.0,
                            "windchill_c": -1.1,
                            "windchill_f": 30.0,
                            "heatindex_c": 2.3,
                            "heatindex_f": 36.1,
                            "dewpoint_c": 1.8,
                            "dewpoint_f": 35.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 74,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.1,
                            "gust_kph": 17.8,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742925600,
                            "time": "2025-03-25 21:00",
                            "temp_c": 2.2,
                            "temp_f": 35.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 8.5,
                            "wind_kph": 13.7,
                            "wind_degree": 159,
                            "wind_dir": "SSE",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.03,
                            "precip_mm": 0.01,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -1.5,
                            "feelslike_f": 29.3,
                            "windchill_c": -1.5,
                            "windchill_f": 29.3,
                            "heatindex_c": 2.2,
                            "heatindex_f": 35.9,
                            "dewpoint_c": 1.6,
                            "dewpoint_f": 34.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 66,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.0,
                            "gust_kph": 19.3,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742929200,
                            "time": "2025-03-25 22:00",
                            "temp_c": 2.1,
                            "temp_f": 35.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 7.8,
                            "wind_kph": 12.6,
                            "wind_degree": 155,
                            "wind_dir": "SSE",
                            "pressure_mb": 1017.0,
                            "pressure_in": 30.02,
                            "precip_mm": 0.01,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 97,
                            "cloud": 100,
                            "feelslike_c": -1.4,
                            "feelslike_f": 29.4,
                            "windchill_c": -1.4,
                            "windchill_f": 29.4,
                            "heatindex_c": 2.1,
                            "heatindex_f": 35.7,
                            "dewpoint_c": 1.6,
                            "dewpoint_f": 34.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 69,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.9,
                            "gust_kph": 17.6,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742932800,
                            "time": "2025-03-25 23:00",
                            "temp_c": 2.0,
                            "temp_f": 35.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                                "code": 1213
                            },
                            "wind_mph": 6.7,
                            "wind_kph": 10.8,
                            "wind_degree": 146,
                            "wind_dir": "SSE",
                            "pressure_mb": 1016.0,
                            "pressure_in": 30.01,
                            "precip_mm": 0.02,
                            "precip_in": 0.0,
                            "snow_cm": 0.01,
                            "humidity": 98,
                            "cloud": 100,
                            "feelslike_c": -1.1,
                            "feelslike_f": 30.0,
                            "windchill_c": -1.1,
                            "windchill_f": 30.0,
                            "heatindex_c": 2.0,
                            "heatindex_f": 35.6,
                            "dewpoint_c": 1.8,
                            "dewpoint_f": 35.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 86,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.3,
                            "gust_kph": 14.9,
                            "uv": 0
                        }
                    ]
                },
                {
                    "lastUpdated": "2025-03-26",
                    "date_epoch": 1742947200,
                    "day": {
                        "maxtemp_c": 3.3,
                        "maxtemp_f": 38.0,
                        "mintemp_c": 1.8,
                        "mintemp_f": 35.2,
                        "avgtemp_c": 2.4,
                        "avgtemp_f": 36.2,
                        "maxwind_mph": 6.3,
                        "maxwind_kph": 10.1,
                        "totalprecip_mm": 0.9,
                        "totalprecip_in": 0.04,
                        "totalsnow_cm": 0.55,
                        "avgvis_km": 7.3,
                        "avgvis_miles": 4.0,
                        "avghumidity": 95,
                        "daily_will_it_rain": 1,
                        "daily_chance_of_rain": 84,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Patchy rain nearby",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                            "code": 1063
                        },
                        "uv": 0.2
                    },
                    "astro": {
                        "sunrise": "06:16 AM",
                        "sunset": "06:56 PM",
                        "moonrise": "05:43 AM",
                        "moonset": "02:27 PM",
                        "moon_phase": "Waning Crescent",
                        "moon_illumination": 16,
                        "is_moon_up": 0,
                        "is_sun_up": 0
                    },
                    "hour": [
                        {
                            "time_epoch": 1742936400,
                            "time": "2025-03-26 00:00",
                            "temp_c": 1.9,
                            "temp_f": 35.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                                "code": 1213
                            },
                            "wind_mph": 6.3,
                            "wind_kph": 10.1,
                            "wind_degree": 138,
                            "wind_dir": "SE",
                            "pressure_mb": 1016.0,
                            "pressure_in": 30.0,
                            "precip_mm": 0.04,
                            "precip_in": 0.0,
                            "snow_cm": 0.03,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": -1.1,
                            "feelslike_f": 30.1,
                            "windchill_c": -1.1,
                            "windchill_f": 30.1,
                            "heatindex_c": 1.9,
                            "heatindex_f": 35.4,
                            "dewpoint_c": 1.7,
                            "dewpoint_f": 35.1,
                            "will_it_rain": 1,
                            "chance_of_rain": 80,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.6,
                            "gust_kph": 13.8,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742940000,
                            "time": "2025-03-26 01:00",
                            "temp_c": 1.8,
                            "temp_f": 35.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                                "code": 1213
                            },
                            "wind_mph": 6.0,
                            "wind_kph": 9.7,
                            "wind_degree": 134,
                            "wind_dir": "SE",
                            "pressure_mb": 1016.0,
                            "pressure_in": 29.99,
                            "precip_mm": 0.05,
                            "precip_in": 0.0,
                            "snow_cm": 0.04,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": -1.1,
                            "feelslike_f": 30.1,
                            "windchill_c": -1.1,
                            "windchill_f": 30.1,
                            "heatindex_c": 1.8,
                            "heatindex_f": 35.3,
                            "dewpoint_c": 1.6,
                            "dewpoint_f": 34.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.2,
                            "gust_kph": 13.2,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742943600,
                            "time": "2025-03-26 02:00",
                            "temp_c": 1.8,
                            "temp_f": 35.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                                "code": 1213
                            },
                            "wind_mph": 4.9,
                            "wind_kph": 7.9,
                            "wind_degree": 121,
                            "wind_dir": "ESE",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.97,
                            "precip_mm": 0.07,
                            "precip_in": 0.0,
                            "snow_cm": 0.05,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": -0.7,
                            "feelslike_f": 30.8,
                            "windchill_c": -0.7,
                            "windchill_f": 30.8,
                            "heatindex_c": 1.8,
                            "heatindex_f": 35.2,
                            "dewpoint_c": 1.6,
                            "dewpoint_f": 34.8,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 6.7,
                            "gust_kph": 10.8,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742947200,
                            "time": "2025-03-26 03:00",
                            "temp_c": 1.8,
                            "temp_f": 35.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                                "code": 1213
                            },
                            "wind_mph": 4.7,
                            "wind_kph": 7.6,
                            "wind_degree": 117,
                            "wind_dir": "ESE",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.96,
                            "precip_mm": 0.05,
                            "precip_in": 0.0,
                            "snow_cm": 0.04,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": -0.5,
                            "feelslike_f": 31.1,
                            "windchill_c": -0.5,
                            "windchill_f": 31.1,
                            "heatindex_c": 1.8,
                            "heatindex_f": 35.2,
                            "dewpoint_c": 1.6,
                            "dewpoint_f": 34.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 6.4,
                            "gust_kph": 10.4,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742950800,
                            "time": "2025-03-26 04:00",
                            "temp_c": 1.8,
                            "temp_f": 35.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Moderate snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                                "code": 1219
                            },
                            "wind_mph": 4.3,
                            "wind_kph": 6.8,
                            "wind_degree": 112,
                            "wind_dir": "ESE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.95,
                            "precip_mm": 0.2,
                            "precip_in": 0.01,
                            "snow_cm": 0.14,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": -0.2,
                            "feelslike_f": 31.6,
                            "windchill_c": -0.2,
                            "windchill_f": 31.6,
                            "heatindex_c": 1.8,
                            "heatindex_f": 35.3,
                            "dewpoint_c": 1.7,
                            "dewpoint_f": 35.0,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 5.0,
                            "vis_miles": 3.0,
                            "gust_mph": 5.8,
                            "gust_kph": 9.4,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742954400,
                            "time": "2025-03-26 05:00",
                            "temp_c": 1.8,
                            "temp_f": 35.3,
                            "is_day": 0,
                            "condition": {
                                "text": "Moderate snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                                "code": 1219
                            },
                            "wind_mph": 3.4,
                            "wind_kph": 5.4,
                            "wind_degree": 109,
                            "wind_dir": "ESE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.94,
                            "precip_mm": 0.09,
                            "precip_in": 0.0,
                            "snow_cm": 0.07,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": 0.3,
                            "feelslike_f": 32.6,
                            "windchill_c": 0.3,
                            "windchill_f": 32.6,
                            "heatindex_c": 1.8,
                            "heatindex_f": 35.3,
                            "dewpoint_c": 1.7,
                            "dewpoint_f": 35.0,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 5.0,
                            "vis_miles": 3.0,
                            "gust_mph": 4.6,
                            "gust_kph": 7.4,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742958000,
                            "time": "2025-03-26 06:00",
                            "temp_c": 1.9,
                            "temp_f": 35.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                                "code": 1213
                            },
                            "wind_mph": 2.9,
                            "wind_kph": 4.7,
                            "wind_degree": 103,
                            "wind_dir": "ESE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.94,
                            "precip_mm": 0.06,
                            "precip_in": 0.0,
                            "snow_cm": 0.04,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": 0.7,
                            "feelslike_f": 33.3,
                            "windchill_c": 0.7,
                            "windchill_f": 33.3,
                            "heatindex_c": 1.9,
                            "heatindex_f": 35.5,
                            "dewpoint_c": 1.8,
                            "dewpoint_f": 35.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 4.0,
                            "gust_kph": 6.4,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1742961600,
                            "time": "2025-03-26 07:00",
                            "temp_c": 1.9,
                            "temp_f": 35.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/326.png",
                                "code": 1213
                            },
                            "wind_mph": 2.5,
                            "wind_kph": 4.0,
                            "wind_degree": 98,
                            "wind_dir": "E",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.05,
                            "precip_in": 0.0,
                            "snow_cm": 0.04,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": 1.1,
                            "feelslike_f": 34.0,
                            "windchill_c": 1.1,
                            "windchill_f": 34.0,
                            "heatindex_c": 1.9,
                            "heatindex_f": 35.5,
                            "dewpoint_c": 1.8,
                            "dewpoint_f": 35.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 84,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 3.4,
                            "gust_kph": 5.5,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1742965200,
                            "time": "2025-03-26 08:00",
                            "temp_c": 2.0,
                            "temp_f": 35.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/326.png",
                                "code": 1213
                            },
                            "wind_mph": 1.6,
                            "wind_kph": 2.5,
                            "wind_degree": 88,
                            "wind_dir": "E",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.94,
                            "precip_mm": 0.03,
                            "precip_in": 0.0,
                            "snow_cm": 0.03,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": 2.0,
                            "feelslike_f": 35.5,
                            "windchill_c": 2.0,
                            "windchill_f": 35.5,
                            "heatindex_c": 2.0,
                            "heatindex_f": 35.5,
                            "dewpoint_c": 1.8,
                            "dewpoint_f": 35.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 84,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 2.2,
                            "gust_kph": 3.5,
                            "uv": 0.1
                        },
                        {
                            "time_epoch": 1742968800,
                            "time": "2025-03-26 09:00",
                            "temp_c": 2.1,
                            "temp_f": 35.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/326.png",
                                "code": 1213
                            },
                            "wind_mph": 1.1,
                            "wind_kph": 1.8,
                            "wind_degree": 58,
                            "wind_dir": "ENE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.94,
                            "precip_mm": 0.07,
                            "precip_in": 0.0,
                            "snow_cm": 0.05,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": 2.1,
                            "feelslike_f": 35.7,
                            "windchill_c": 2.1,
                            "windchill_f": 35.7,
                            "heatindex_c": 2.1,
                            "heatindex_f": 35.7,
                            "dewpoint_c": 1.9,
                            "dewpoint_f": 35.4,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 1.5,
                            "gust_kph": 2.5,
                            "uv": 0.1
                        },
                        {
                            "time_epoch": 1742972400,
                            "time": "2025-03-26 10:00",
                            "temp_c": 2.1,
                            "temp_f": 35.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/326.png",
                                "code": 1213
                            },
                            "wind_mph": 1.1,
                            "wind_kph": 1.8,
                            "wind_degree": 38,
                            "wind_dir": "NE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.04,
                            "precip_in": 0.0,
                            "snow_cm": 0.03,
                            "humidity": 99,
                            "cloud": 100,
                            "feelslike_c": 2.1,
                            "feelslike_f": 35.7,
                            "windchill_c": 2.1,
                            "windchill_f": 35.7,
                            "heatindex_c": 2.1,
                            "heatindex_f": 35.7,
                            "dewpoint_c": 1.9,
                            "dewpoint_f": 35.4,
                            "will_it_rain": 1,
                            "chance_of_rain": 80,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 1.5,
                            "gust_kph": 2.5,
                            "uv": 0.3
                        },
                        {
                            "time_epoch": 1742976000,
                            "time": "2025-03-26 11:00",
                            "temp_c": 2.2,
                            "temp_f": 35.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Fog",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                                "code": 1135
                            },
                            "wind_mph": 0.9,
                            "wind_kph": 1.4,
                            "wind_degree": 45,
                            "wind_dir": "NE",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.02,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 98,
                            "cloud": 100,
                            "feelslike_c": 2.2,
                            "feelslike_f": 35.9,
                            "windchill_c": 2.2,
                            "windchill_f": 35.9,
                            "heatindex_c": 2.2,
                            "heatindex_f": 35.9,
                            "dewpoint_c": 1.9,
                            "dewpoint_f": 35.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 65,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 1.3,
                            "gust_kph": 2.0,
                            "uv": 0.4
                        },
                        {
                            "time_epoch": 1742979600,
                            "time": "2025-03-26 12:00",
                            "temp_c": 2.4,
                            "temp_f": 36.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Fog",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                                "code": 1135
                            },
                            "wind_mph": 0.7,
                            "wind_kph": 1.1,
                            "wind_degree": 7,
                            "wind_dir": "N",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.03,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 98,
                            "cloud": 100,
                            "feelslike_c": 2.4,
                            "feelslike_f": 36.3,
                            "windchill_c": 2.4,
                            "windchill_f": 36.3,
                            "heatindex_c": 2.4,
                            "heatindex_f": 36.3,
                            "dewpoint_c": 2.0,
                            "dewpoint_f": 35.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 61,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 0.9,
                            "gust_kph": 1.5,
                            "uv": 0.6
                        },
                        {
                            "time_epoch": 1742983200,
                            "time": "2025-03-26 13:00",
                            "temp_c": 2.4,
                            "temp_f": 36.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Fog",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/248.png",
                                "code": 1135
                            },
                            "wind_mph": 1.1,
                            "wind_kph": 1.8,
                            "wind_degree": 315,
                            "wind_dir": "NW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.03,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 97,
                            "cloud": 100,
                            "feelslike_c": 2.4,
                            "feelslike_f": 36.3,
                            "windchill_c": 2.4,
                            "windchill_f": 36.3,
                            "heatindex_c": 2.4,
                            "heatindex_f": 36.3,
                            "dewpoint_c": 2.0,
                            "dewpoint_f": 35.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 62,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 1.5,
                            "gust_kph": 2.5,
                            "uv": 0.8
                        },
                        {
                            "time_epoch": 1742986800,
                            "time": "2025-03-26 14:00",
                            "temp_c": 2.5,
                            "temp_f": 36.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Mist",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/143.png",
                                "code": 1030
                            },
                            "wind_mph": 1.8,
                            "wind_kph": 2.9,
                            "wind_degree": 299,
                            "wind_dir": "WNW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.03,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 97,
                            "cloud": 100,
                            "feelslike_c": 2.5,
                            "feelslike_f": 36.5,
                            "windchill_c": 2.5,
                            "windchill_f": 36.5,
                            "heatindex_c": 2.5,
                            "heatindex_f": 36.5,
                            "dewpoint_c": 2.0,
                            "dewpoint_f": 35.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 68,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 2.5,
                            "gust_kph": 4.0,
                            "uv": 0.9
                        },
                        {
                            "time_epoch": 1742990400,
                            "time": "2025-03-26 15:00",
                            "temp_c": 2.7,
                            "temp_f": 36.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Mist",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/143.png",
                                "code": 1030
                            },
                            "wind_mph": 1.6,
                            "wind_kph": 2.5,
                            "wind_degree": 290,
                            "wind_dir": "WNW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.02,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": 2.7,
                            "feelslike_f": 36.8,
                            "windchill_c": 2.7,
                            "windchill_f": 36.8,
                            "heatindex_c": 2.7,
                            "heatindex_f": 36.8,
                            "dewpoint_c": 2.1,
                            "dewpoint_f": 35.7,
                            "will_it_rain": 1,
                            "chance_of_rain": 83,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 2.2,
                            "gust_kph": 3.6,
                            "uv": 0.7
                        },
                        {
                            "time_epoch": 1742994000,
                            "time": "2025-03-26 16:00",
                            "temp_c": 3.0,
                            "temp_f": 37.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 2.7,
                            "wind_kph": 4.3,
                            "wind_degree": 283,
                            "wind_dir": "WNW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 90,
                            "cloud": 100,
                            "feelslike_c": 2.2,
                            "feelslike_f": 35.9,
                            "windchill_c": 2.2,
                            "windchill_f": 35.9,
                            "heatindex_c": 3.0,
                            "heatindex_f": 37.5,
                            "dewpoint_c": 1.6,
                            "dewpoint_f": 34.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 3.8,
                            "gust_kph": 6.1,
                            "uv": 0.3
                        },
                        {
                            "time_epoch": 1742997600,
                            "time": "2025-03-26 17:00",
                            "temp_c": 3.3,
                            "temp_f": 38.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 2.7,
                            "wind_kph": 4.3,
                            "wind_degree": 284,
                            "wind_dir": "WNW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.93,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 86,
                            "cloud": 100,
                            "feelslike_c": 2.5,
                            "feelslike_f": 36.4,
                            "windchill_c": 2.5,
                            "windchill_f": 36.4,
                            "heatindex_c": 3.3,
                            "heatindex_f": 38.0,
                            "dewpoint_c": 1.2,
                            "dewpoint_f": 34.1,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 3.9,
                            "gust_kph": 6.3,
                            "uv": 0.1
                        },
                        {
                            "time_epoch": 1743001200,
                            "time": "2025-03-26 18:00",
                            "temp_c": 3.2,
                            "temp_f": 37.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 1.6,
                            "wind_kph": 2.5,
                            "wind_degree": 252,
                            "wind_dir": "WSW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.94,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 85,
                            "cloud": 100,
                            "feelslike_c": 3.2,
                            "feelslike_f": 37.8,
                            "windchill_c": 3.2,
                            "windchill_f": 37.8,
                            "heatindex_c": 3.2,
                            "heatindex_f": 37.8,
                            "dewpoint_c": 0.9,
                            "dewpoint_f": 33.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 2.5,
                            "gust_kph": 4.0,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1743004800,
                            "time": "2025-03-26 19:00",
                            "temp_c": 3.3,
                            "temp_f": 38.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 2.0,
                            "wind_kph": 3.2,
                            "wind_degree": 210,
                            "wind_dir": "SSW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.95,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 84,
                            "cloud": 100,
                            "feelslike_c": 3.0,
                            "feelslike_f": 37.5,
                            "windchill_c": 3.0,
                            "windchill_f": 37.5,
                            "heatindex_c": 3.3,
                            "heatindex_f": 38.0,
                            "dewpoint_c": 1.0,
                            "dewpoint_f": 33.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 3.2,
                            "gust_kph": 5.2,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743008400,
                            "time": "2025-03-26 20:00",
                            "temp_c": 3.2,
                            "temp_f": 37.7,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 3.4,
                            "wind_kph": 5.4,
                            "wind_degree": 202,
                            "wind_dir": "SSW",
                            "pressure_mb": 1014.0,
                            "pressure_in": 29.96,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 86,
                            "cloud": 100,
                            "feelslike_c": 1.8,
                            "feelslike_f": 35.3,
                            "windchill_c": 1.8,
                            "windchill_f": 35.3,
                            "heatindex_c": 3.2,
                            "heatindex_f": 37.7,
                            "dewpoint_c": 1.1,
                            "dewpoint_f": 33.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 5.5,
                            "gust_kph": 8.8,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743012000,
                            "time": "2025-03-26 21:00",
                            "temp_c": 2.8,
                            "temp_f": 37.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                "code": 1006
                            },
                            "wind_mph": 4.0,
                            "wind_kph": 6.5,
                            "wind_degree": 204,
                            "wind_dir": "SSW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.96,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 90,
                            "cloud": 75,
                            "feelslike_c": 1.0,
                            "feelslike_f": 33.8,
                            "windchill_c": 1.0,
                            "windchill_f": 33.8,
                            "heatindex_c": 2.8,
                            "heatindex_f": 37.0,
                            "dewpoint_c": 1.3,
                            "dewpoint_f": 34.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 6.9,
                            "gust_kph": 11.1,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743015600,
                            "time": "2025-03-26 22:00",
                            "temp_c": 2.5,
                            "temp_f": 36.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/119.png",
                                "code": 1006
                            },
                            "wind_mph": 4.5,
                            "wind_kph": 7.2,
                            "wind_degree": 205,
                            "wind_dir": "SSW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.96,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 93,
                            "cloud": 64,
                            "feelslike_c": 0.4,
                            "feelslike_f": 32.8,
                            "windchill_c": 0.4,
                            "windchill_f": 32.8,
                            "heatindex_c": 2.5,
                            "heatindex_f": 36.5,
                            "dewpoint_c": 1.4,
                            "dewpoint_f": 34.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 7.8,
                            "gust_kph": 12.5,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743019200,
                            "time": "2025-03-26 23:00",
                            "temp_c": 2.1,
                            "temp_f": 35.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Mist",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/143.png",
                                "code": 1030
                            },
                            "wind_mph": 4.7,
                            "wind_kph": 7.6,
                            "wind_degree": 201,
                            "wind_dir": "SSW",
                            "pressure_mb": 1015.0,
                            "pressure_in": 29.96,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 95,
                            "cloud": 90,
                            "feelslike_c": -0.1,
                            "feelslike_f": 31.9,
                            "windchill_c": -0.1,
                            "windchill_f": 31.9,
                            "heatindex_c": 2.2,
                            "heatindex_f": 35.9,
                            "dewpoint_c": 1.4,
                            "dewpoint_f": 34.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 8.5,
                            "gust_kph": 13.6,
                            "uv": 0
                        }
                    ]
                }
            ]
        }
    }
""".trimIndent()