package com.softcat.weatherapp.testing.jsonMocks

val weatherForecastJson = """
    {
        "location": {
            "name": "Moscow",
            "region": "Moscow City",
            "country": "Russia",
            "lat": 55.7522,
            "lon": 37.6156,
            "tz_id": "Europe/Moscow",
            "localtime_epoch": 1743874799,
            "localtime": "2025-04-05 20:39"
        },
        "current": {
            "last_updated_epoch": 1743874200,
            "last_updated": "2025-04-05 20:30",
            "temp_c": 3.3,
            "temp_f": 37.9,
            "is_day": 0,
            "condition": {
                "text": "Light snow",
                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                "code": 1213
            },
            "wind_mph": 13.2,
            "wind_kph": 21.2,
            "wind_degree": 46,
            "wind_dir": "NE",
            "pressure_mb": 1004.0,
            "pressure_in": 29.65,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 60,
            "cloud": 75,
            "feelslike_c": -1.2,
            "feelslike_f": 29.8,
            "windchill_c": -1.7,
            "windchill_f": 29.0,
            "heatindex_c": 3.0,
            "heatindex_f": 37.3,
            "dewpoint_c": -5.7,
            "dewpoint_f": 21.7,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "uv": 0.0,
            "gust_mph": 17.0,
            "gust_kph": 27.3,
            "air_quality": {
                "co": 497.65,
                "no2": 65.86,
                "o3": 48.0,
                "so2": 36.26,
                "pm2_5": 19.98,
                "pm10": 28.12,
                "us-epa-index": 2,
                "gb-defra-index": 2
            }
        },
        "forecast": {
            "forecastday": [
                {
                    "date": "2025-04-05",
                    "date_epoch": 1743811200,
                    "day": {
                        "maxtemp_c": 5.4,
                        "maxtemp_f": 41.7,
                        "mintemp_c": 1.6,
                        "mintemp_f": 34.8,
                        "avgtemp_c": 4.1,
                        "avgtemp_f": 39.4,
                        "maxwind_mph": 14.5,
                        "maxwind_kph": 23.4,
                        "totalprecip_mm": 0.05,
                        "totalprecip_in": 0.0,
                        "totalsnow_cm": 0.0,
                        "avgvis_km": 10.0,
                        "avgvis_miles": 6.0,
                        "avghumidity": 58,
                        "daily_will_it_rain": 0,
                        "daily_chance_of_rain": 0,
                        "daily_will_it_snow": 0,
                        "daily_chance_of_snow": 0,
                        "condition": {
                            "text": "Overcast ",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            "code": 1009
                        },
                        "uv": 0.4
                    },
                    "astro": {
                        "sunrise": "05:50 AM",
                        "sunset": "07:16 PM",
                        "moonrise": "09:42 AM",
                        "moonset": "04:01 AM",
                        "moon_phase": "First Quarter",
                        "moon_illumination": 49,
                        "is_moon_up": 1,
                        "is_sun_up": 0
                    },
                    "hour": [
                        {
                            "time_epoch": 1743800400,
                            "time": "2025-04-05 00:00",
                            "temp_c": 5.9,
                            "temp_f": 42.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 7.4,
                            "wind_kph": 11.9,
                            "wind_degree": 316,
                            "wind_dir": "NW",
                            "pressure_mb": 1003.0,
                            "pressure_in": 29.63,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 55,
                            "cloud": 7,
                            "feelslike_c": 3.3,
                            "feelslike_f": 38.0,
                            "windchill_c": 3.3,
                            "windchill_f": 38.0,
                            "heatindex_c": 5.9,
                            "heatindex_f": 42.5,
                            "dewpoint_c": -2.6,
                            "dewpoint_f": 27.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 10.3,
                            "gust_kph": 16.6,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743804000,
                            "time": "2025-04-05 01:00",
                            "temp_c": 5.2,
                            "temp_f": 41.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.7,
                            "wind_kph": 10.8,
                            "wind_degree": 314,
                            "wind_dir": "NW",
                            "pressure_mb": 1003.0,
                            "pressure_in": 29.62,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 58,
                            "cloud": 9,
                            "feelslike_c": 2.7,
                            "feelslike_f": 36.9,
                            "windchill_c": 2.7,
                            "windchill_f": 36.9,
                            "heatindex_c": 5.2,
                            "heatindex_f": 41.4,
                            "dewpoint_c": -2.3,
                            "dewpoint_f": 27.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.4,
                            "gust_kph": 15.1,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743807600,
                            "time": "2025-04-05 02:00",
                            "temp_c": 4.7,
                            "temp_f": 40.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.7,
                            "wind_kph": 10.8,
                            "wind_degree": 318,
                            "wind_dir": "NW",
                            "pressure_mb": 1003.0,
                            "pressure_in": 29.62,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 62,
                            "cloud": 8,
                            "feelslike_c": 2.1,
                            "feelslike_f": 35.8,
                            "windchill_c": 2.1,
                            "windchill_f": 35.8,
                            "heatindex_c": 4.7,
                            "heatindex_f": 40.4,
                            "dewpoint_c": -2.0,
                            "dewpoint_f": 28.4,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.3,
                            "gust_kph": 15.0,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743811200,
                            "time": "2025-04-05 03:00",
                            "temp_c": 4.1,
                            "temp_f": 39.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Clear ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/113.png",
                                "code": 1000
                            },
                            "wind_mph": 6.5,
                            "wind_kph": 10.4,
                            "wind_degree": 325,
                            "wind_dir": "NW",
                            "pressure_mb": 1003.0,
                            "pressure_in": 29.62,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 65,
                            "cloud": 21,
                            "feelslike_c": 1.5,
                            "feelslike_f": 34.7,
                            "windchill_c": 1.5,
                            "windchill_f": 34.7,
                            "heatindex_c": 4.1,
                            "heatindex_f": 39.4,
                            "dewpoint_c": -2.0,
                            "dewpoint_f": 28.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 9.1,
                            "gust_kph": 14.6,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743814800,
                            "time": "2025-04-05 04:00",
                            "temp_c": 3.7,
                            "temp_f": 38.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 6.3,
                            "wind_kph": 10.1,
                            "wind_degree": 331,
                            "wind_dir": "NNW",
                            "pressure_mb": 1003.0,
                            "pressure_in": 29.63,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 67,
                            "cloud": 29,
                            "feelslike_c": 1.0,
                            "feelslike_f": 33.9,
                            "windchill_c": 1.0,
                            "windchill_f": 33.9,
                            "heatindex_c": 3.7,
                            "heatindex_f": 38.6,
                            "dewpoint_c": -1.9,
                            "dewpoint_f": 28.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.6,
                            "gust_kph": 13.8,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743818400,
                            "time": "2025-04-05 05:00",
                            "temp_c": 3.1,
                            "temp_f": 37.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 5.6,
                            "wind_kph": 9.0,
                            "wind_degree": 349,
                            "wind_dir": "N",
                            "pressure_mb": 1003.0,
                            "pressure_in": 29.63,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 69,
                            "cloud": 49,
                            "feelslike_c": 0.6,
                            "feelslike_f": 33.2,
                            "windchill_c": 0.6,
                            "windchill_f": 33.2,
                            "heatindex_c": 3.1,
                            "heatindex_f": 37.6,
                            "dewpoint_c": -2.0,
                            "dewpoint_f": 28.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 7.7,
                            "gust_kph": 12.4,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743822000,
                            "time": "2025-04-05 06:00",
                            "temp_c": 3.0,
                            "temp_f": 37.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 5.8,
                            "wind_kph": 9.4,
                            "wind_degree": 0,
                            "wind_dir": "N",
                            "pressure_mb": 1003.0,
                            "pressure_in": 29.63,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 70,
                            "cloud": 61,
                            "feelslike_c": 0.5,
                            "feelslike_f": 32.8,
                            "windchill_c": 0.5,
                            "windchill_f": 32.8,
                            "heatindex_c": 3.0,
                            "heatindex_f": 37.5,
                            "dewpoint_c": -2.0,
                            "dewpoint_f": 28.5,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 7.5,
                            "gust_kph": 12.1,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1743825600,
                            "time": "2025-04-05 07:00",
                            "temp_c": 3.4,
                            "temp_f": 38.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                                "code": 1006
                            },
                            "wind_mph": 5.8,
                            "wind_kph": 9.4,
                            "wind_degree": 12,
                            "wind_dir": "NNE",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.64,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 67,
                            "cloud": 66,
                            "feelslike_c": 1.0,
                            "feelslike_f": 33.7,
                            "windchill_c": 1.0,
                            "windchill_f": 33.7,
                            "heatindex_c": 3.4,
                            "heatindex_f": 38.2,
                            "dewpoint_c": -2.1,
                            "dewpoint_f": 28.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 7.0,
                            "gust_kph": 11.2,
                            "uv": 0.2
                        },
                        {
                            "time_epoch": 1743829200,
                            "time": "2025-04-05 08:00",
                            "temp_c": 4.0,
                            "temp_f": 39.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                                "code": 1006
                            },
                            "wind_mph": 5.8,
                            "wind_kph": 9.4,
                            "wind_degree": 13,
                            "wind_dir": "NNE",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.64,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 63,
                            "cloud": 75,
                            "feelslike_c": 1.6,
                            "feelslike_f": 34.9,
                            "windchill_c": 1.6,
                            "windchill_f": 34.9,
                            "heatindex_c": 4.0,
                            "heatindex_f": 39.2,
                            "dewpoint_c": -2.3,
                            "dewpoint_f": 27.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 6.7,
                            "gust_kph": 10.8,
                            "uv": 0.5
                        },
                        {
                            "time_epoch": 1743832800,
                            "time": "2025-04-05 09:00",
                            "temp_c": 4.7,
                            "temp_f": 40.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                                "code": 1006
                            },
                            "wind_mph": 5.6,
                            "wind_kph": 9.0,
                            "wind_degree": 12,
                            "wind_dir": "NNE",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.64,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 59,
                            "cloud": 77,
                            "feelslike_c": 2.6,
                            "feelslike_f": 36.6,
                            "windchill_c": 2.6,
                            "windchill_f": 36.6,
                            "heatindex_c": 4.7,
                            "heatindex_f": 40.5,
                            "dewpoint_c": -2.6,
                            "dewpoint_f": 27.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 6.4,
                            "gust_kph": 10.4,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1743836400,
                            "time": "2025-04-05 10:00",
                            "temp_c": 5.2,
                            "temp_f": 41.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 6.0,
                            "wind_kph": 9.7,
                            "wind_degree": 8,
                            "wind_dir": "N",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.64,
                            "precip_mm": 0.02,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 55,
                            "cloud": 100,
                            "feelslike_c": 3.0,
                            "feelslike_f": 37.4,
                            "windchill_c": 3.0,
                            "windchill_f": 37.4,
                            "heatindex_c": 5.2,
                            "heatindex_f": 41.4,
                            "dewpoint_c": -3.0,
                            "dewpoint_f": 26.6,
                            "will_it_rain": 1,
                            "chance_of_rain": 88,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 7.0,
                            "gust_kph": 11.2,
                            "uv": 1.3
                        },
                        {
                            "time_epoch": 1743840000,
                            "time": "2025-04-05 11:00",
                            "temp_c": 5.4,
                            "temp_f": 41.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/176.png",
                                "code": 1063
                            },
                            "wind_mph": 6.9,
                            "wind_kph": 11.2,
                            "wind_degree": 13,
                            "wind_dir": "NNE",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.65,
                            "precip_mm": 0.01,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 52,
                            "cloud": 100,
                            "feelslike_c": 2.9,
                            "feelslike_f": 37.2,
                            "windchill_c": 2.9,
                            "windchill_f": 37.2,
                            "heatindex_c": 5.4,
                            "heatindex_f": 41.7,
                            "dewpoint_c": -3.6,
                            "dewpoint_f": 25.5,
                            "will_it_rain": 1,
                            "chance_of_rain": 85,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 8.0,
                            "gust_kph": 12.9,
                            "uv": 1.1
                        },
                        {
                            "time_epoch": 1743843600,
                            "time": "2025-04-05 12:00",
                            "temp_c": 4.9,
                            "temp_f": 40.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 9.6,
                            "wind_kph": 15.5,
                            "wind_degree": 18,
                            "wind_dir": "NNE",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.66,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 56,
                            "cloud": 100,
                            "feelslike_c": 1.6,
                            "feelslike_f": 34.8,
                            "windchill_c": 1.6,
                            "windchill_f": 34.8,
                            "heatindex_c": 4.9,
                            "heatindex_f": 40.9,
                            "dewpoint_c": -3.2,
                            "dewpoint_f": 26.3,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 11.1,
                            "gust_kph": 17.8,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1743847200,
                            "time": "2025-04-05 13:00",
                            "temp_c": 4.7,
                            "temp_f": 40.5,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 11.0,
                            "wind_kph": 17.6,
                            "wind_degree": 30,
                            "wind_dir": "NNE",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.66,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 57,
                            "cloud": 90,
                            "feelslike_c": 1.0,
                            "feelslike_f": 33.8,
                            "windchill_c": 1.0,
                            "windchill_f": 33.8,
                            "heatindex_c": 4.7,
                            "heatindex_f": 40.5,
                            "dewpoint_c": -3.0,
                            "dewpoint_f": 26.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.6,
                            "gust_kph": 20.3,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1743850800,
                            "time": "2025-04-05 14:00",
                            "temp_c": 5.0,
                            "temp_f": 41.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 10.5,
                            "wind_kph": 16.9,
                            "wind_degree": 39,
                            "wind_dir": "NE",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.66,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 54,
                            "cloud": 100,
                            "feelslike_c": 1.5,
                            "feelslike_f": 34.7,
                            "windchill_c": 1.5,
                            "windchill_f": 34.7,
                            "heatindex_c": 5.0,
                            "heatindex_f": 41.1,
                            "dewpoint_c": -3.5,
                            "dewpoint_f": 25.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.1,
                            "gust_kph": 19.5,
                            "uv": 1.0
                        },
                        {
                            "time_epoch": 1743854400,
                            "time": "2025-04-05 15:00",
                            "temp_c": 5.2,
                            "temp_f": 41.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 10.5,
                            "wind_kph": 16.9,
                            "wind_degree": 41,
                            "wind_dir": "NE",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.66,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 51,
                            "cloud": 100,
                            "feelslike_c": 1.7,
                            "feelslike_f": 35.0,
                            "windchill_c": 1.7,
                            "windchill_f": 35.0,
                            "heatindex_c": 5.2,
                            "heatindex_f": 41.3,
                            "dewpoint_c": -4.1,
                            "dewpoint_f": 24.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 12.1,
                            "gust_kph": 19.5,
                            "uv": 0.7
                        },
                        {
                            "time_epoch": 1743858000,
                            "time": "2025-04-05 16:00",
                            "temp_c": 5.0,
                            "temp_f": 41.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 11.4,
                            "wind_kph": 18.4,
                            "wind_degree": 39,
                            "wind_dir": "NE",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.66,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 50,
                            "cloud": 100,
                            "feelslike_c": 1.3,
                            "feelslike_f": 34.4,
                            "windchill_c": 1.3,
                            "windchill_f": 34.4,
                            "heatindex_c": 5.0,
                            "heatindex_f": 41.1,
                            "dewpoint_c": -4.5,
                            "dewpoint_f": 23.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 13.1,
                            "gust_kph": 21.1,
                            "uv": 0.4
                        },
                        {
                            "time_epoch": 1743861600,
                            "time": "2025-04-05 17:00",
                            "temp_c": 4.7,
                            "temp_f": 40.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                                "code": 1009
                            },
                            "wind_mph": 12.1,
                            "wind_kph": 19.4,
                            "wind_degree": 42,
                            "wind_dir": "NE",
                            "pressure_mb": 1005.0,
                            "pressure_in": 29.67,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 51,
                            "cloud": 100,
                            "feelslike_c": 0.7,
                            "feelslike_f": 33.3,
                            "windchill_c": 0.7,
                            "windchill_f": 33.3,
                            "heatindex_c": 4.7,
                            "heatindex_f": 40.4,
                            "dewpoint_c": -4.5,
                            "dewpoint_f": 23.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 14.6,
                            "gust_kph": 23.5,
                            "uv": 0.3
                        },
                        {
                            "time_epoch": 1743865200,
                            "time": "2025-04-05 18:00",
                            "temp_c": 4.0,
                            "temp_f": 39.2,
                            "is_day": 1,
                            "condition": {
                                "text": "Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/119.png",
                                "code": 1006
                            },
                            "wind_mph": 12.5,
                            "wind_kph": 20.2,
                            "wind_degree": 45,
                            "wind_dir": "NE",
                            "pressure_mb": 1005.0,
                            "pressure_in": 29.68,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 54,
                            "cloud": 84,
                            "feelslike_c": -0.2,
                            "feelslike_f": 31.6,
                            "windchill_c": -0.2,
                            "windchill_f": 31.6,
                            "heatindex_c": 4.0,
                            "heatindex_f": 39.2,
                            "dewpoint_c": -4.4,
                            "dewpoint_f": 24.2,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 15.5,
                            "gust_kph": 25.0,
                            "uv": 0.1
                        },
                        {
                            "time_epoch": 1743868800,
                            "time": "2025-04-05 19:00",
                            "temp_c": 3.5,
                            "temp_f": 38.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Partly Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                                "code": 1003
                            },
                            "wind_mph": 12.5,
                            "wind_kph": 20.2,
                            "wind_degree": 45,
                            "wind_dir": "NE",
                            "pressure_mb": 1005.0,
                            "pressure_in": 29.69,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 53,
                            "cloud": 37,
                            "feelslike_c": -0.8,
                            "feelslike_f": 30.5,
                            "windchill_c": -0.8,
                            "windchill_f": 30.5,
                            "heatindex_c": 3.5,
                            "heatindex_f": 38.4,
                            "dewpoint_c": -5.1,
                            "dewpoint_f": 22.8,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 15.9,
                            "gust_kph": 25.6,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1743872400,
                            "time": "2025-04-05 20:00",
                            "temp_c": 3.3,
                            "temp_f": 37.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Light snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/326.png",
                                "code": 1213
                            },
                            "wind_mph": 13.2,
                            "wind_kph": 21.2,
                            "wind_degree": 46,
                            "wind_dir": "NE",
                            "pressure_mb": 1004.0,
                            "pressure_in": 29.65,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 60,
                            "cloud": 75,
                            "feelslike_c": -1.7,
                            "feelslike_f": 29.0,
                            "windchill_c": -1.7,
                            "windchill_f": 29.0,
                            "heatindex_c": 3.0,
                            "heatindex_f": 37.3,
                            "dewpoint_c": -5.7,
                            "dewpoint_f": 21.7,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.0,
                            "gust_kph": 27.3,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743876000,
                            "time": "2025-04-05 21:00",
                            "temp_c": 2.6,
                            "temp_f": 36.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Overcast ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/122.png",
                                "code": 1009
                            },
                            "wind_mph": 13.2,
                            "wind_kph": 21.2,
                            "wind_degree": 44,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.72,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 54,
                            "cloud": 100,
                            "feelslike_c": -2.2,
                            "feelslike_f": 28.1,
                            "windchill_c": -2.2,
                            "windchill_f": 28.1,
                            "heatindex_c": 2.6,
                            "heatindex_f": 36.6,
                            "dewpoint_c": -5.8,
                            "dewpoint_f": 21.6,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.1,
                            "gust_kph": 27.5,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743879600,
                            "time": "2025-04-05 22:00",
                            "temp_c": 2.2,
                            "temp_f": 35.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Partly Cloudy ",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
                                "code": 1003
                            },
                            "wind_mph": 14.5,
                            "wind_kph": 23.4,
                            "wind_degree": 40,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.7,
                            "precip_mm": 0.0,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 56,
                            "cloud": 60,
                            "feelslike_c": -2.9,
                            "feelslike_f": 26.7,
                            "windchill_c": -2.9,
                            "windchill_f": 26.7,
                            "heatindex_c": 2.2,
                            "heatindex_f": 35.9,
                            "dewpoint_c": -5.6,
                            "dewpoint_f": 21.9,
                            "will_it_rain": 0,
                            "chance_of_rain": 0,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 18.1,
                            "gust_kph": 29.2,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743883200,
                            "time": "2025-04-05 23:00",
                            "temp_c": 1.6,
                            "temp_f": 34.8,
                            "is_day": 0,
                            "condition": {
                                "text": "Patchy rain nearby",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/176.png",
                                "code": 1063
                            },
                            "wind_mph": 14.1,
                            "wind_kph": 22.7,
                            "wind_degree": 38,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.71,
                            "precip_mm": 0.01,
                            "precip_in": 0.0,
                            "snow_cm": 0.0,
                            "humidity": 58,
                            "cloud": 66,
                            "feelslike_c": -3.6,
                            "feelslike_f": 25.5,
                            "windchill_c": -3.6,
                            "windchill_f": 25.5,
                            "heatindex_c": 1.6,
                            "heatindex_f": 34.8,
                            "dewpoint_c": -5.7,
                            "dewpoint_f": 21.8,
                            "will_it_rain": 1,
                            "chance_of_rain": 71,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 10.0,
                            "vis_miles": 6.0,
                            "gust_mph": 17.9,
                            "gust_kph": 28.8,
                            "uv": 0
                        }
                    ]
                },
                {
                    "date": "2025-04-06",
                    "date_epoch": 1743897600,
                    "day": {
                        "maxtemp_c": -1.5,
                        "maxtemp_f": 29.3,
                        "mintemp_c": -3.3,
                        "mintemp_f": 26.1,
                        "avgtemp_c": -1.7,
                        "avgtemp_f": 28.9,
                        "maxwind_mph": 19.0,
                        "maxwind_kph": 30.6,
                        "totalprecip_mm": 30.15,
                        "totalprecip_in": 1.19,
                        "totalsnow_cm": 7.91,
                        "avgvis_km": 1.2,
                        "avgvis_miles": 0.0,
                        "avghumidity": 90,
                        "daily_will_it_rain": 1,
                        "daily_chance_of_rain": 88,
                        "daily_will_it_snow": 1,
                        "daily_chance_of_snow": 84,
                        "condition": {
                            "text": "Blizzard",
                            "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                            "code": 1117
                        },
                        "uv": 0.4
                    },
                    "astro": {
                        "sunrise": "05:48 AM",
                        "sunset": "07:18 PM",
                        "moonrise": "11:10 AM",
                        "moonset": "04:27 AM",
                        "moon_phase": "Waxing Gibbous",
                        "moon_illumination": 60,
                        "is_moon_up": 1,
                        "is_sun_up": 0
                    },
                    "hour": [
                        {
                            "time_epoch": 1743886800,
                            "time": "2025-04-06 00:00",
                            "temp_c": 1.4,
                            "temp_f": 34.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Moderate snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                                "code": 1219
                            },
                            "wind_mph": 14.8,
                            "wind_kph": 23.8,
                            "wind_degree": 40,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.71,
                            "precip_mm": 0.09,
                            "precip_in": 0.0,
                            "snow_cm": 0.06,
                            "humidity": 58,
                            "cloud": 83,
                            "feelslike_c": -3.9,
                            "feelslike_f": 24.9,
                            "windchill_c": -3.9,
                            "windchill_f": 24.9,
                            "heatindex_c": 1.4,
                            "heatindex_f": 34.6,
                            "dewpoint_c": -5.8,
                            "dewpoint_f": 21.6,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 0,
                            "chance_of_snow": 0,
                            "vis_km": 5.0,
                            "vis_miles": 3.0,
                            "gust_mph": 18.1,
                            "gust_kph": 29.1,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743890400,
                            "time": "2025-04-06 01:00",
                            "temp_c": 0.6,
                            "temp_f": 33.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Moderate snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/332.png",
                                "code": 1219
                            },
                            "wind_mph": 15.7,
                            "wind_kph": 25.2,
                            "wind_degree": 46,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.71,
                            "precip_mm": 0.2,
                            "precip_in": 0.01,
                            "snow_cm": 0.15,
                            "humidity": 66,
                            "cloud": 100,
                            "feelslike_c": -5.2,
                            "feelslike_f": 22.7,
                            "windchill_c": -5.2,
                            "windchill_f": 22.7,
                            "heatindex_c": 0.6,
                            "heatindex_f": 33.1,
                            "dewpoint_c": -5.1,
                            "dewpoint_f": 22.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 5.0,
                            "vis_miles": 3.0,
                            "gust_mph": 18.9,
                            "gust_kph": 30.5,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743894000,
                            "time": "2025-04-06 02:00",
                            "temp_c": -0.4,
                            "temp_f": 31.4,
                            "is_day": 0,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/230.png",
                                "code": 1117
                            },
                            "wind_mph": 17.0,
                            "wind_kph": 27.4,
                            "wind_degree": 46,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.69,
                            "precip_mm": 0.28,
                            "precip_in": 0.01,
                            "snow_cm": 0.0,
                            "humidity": 76,
                            "cloud": 100,
                            "feelslike_c": -6.7,
                            "feelslike_f": 20.0,
                            "windchill_c": -6.7,
                            "windchill_f": 20.0,
                            "heatindex_c": -0.4,
                            "heatindex_f": 31.4,
                            "dewpoint_c": -4.1,
                            "dewpoint_f": 24.7,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 74,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 20.6,
                            "gust_kph": 33.2,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743897600,
                            "time": "2025-04-06 03:00",
                            "temp_c": -0.8,
                            "temp_f": 30.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/230.png",
                                "code": 1117
                            },
                            "wind_mph": 17.0,
                            "wind_kph": 27.4,
                            "wind_degree": 44,
                            "wind_dir": "NE",
                            "pressure_mb": 1005.0,
                            "pressure_in": 29.69,
                            "precip_mm": 0.55,
                            "precip_in": 0.02,
                            "snow_cm": 0.0,
                            "humidity": 81,
                            "cloud": 100,
                            "feelslike_c": -7.3,
                            "feelslike_f": 19.0,
                            "windchill_c": -7.3,
                            "windchill_f": 19.0,
                            "heatindex_c": -0.8,
                            "heatindex_f": 30.5,
                            "dewpoint_c": -3.6,
                            "dewpoint_f": 25.5,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 87,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 21.0,
                            "gust_kph": 33.8,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743901200,
                            "time": "2025-04-06 04:00",
                            "temp_c": -1.3,
                            "temp_f": 29.6,
                            "is_day": 0,
                            "condition": {
                                "text": "Heavy snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                                "code": 1225
                            },
                            "wind_mph": 16.8,
                            "wind_kph": 27.0,
                            "wind_degree": 45,
                            "wind_dir": "NE",
                            "pressure_mb": 1005.0,
                            "pressure_in": 29.69,
                            "precip_mm": 1.11,
                            "precip_in": 0.04,
                            "snow_cm": 0.8,
                            "humidity": 88,
                            "cloud": 100,
                            "feelslike_c": -7.9,
                            "feelslike_f": 17.8,
                            "windchill_c": -7.9,
                            "windchill_f": 17.8,
                            "heatindex_c": -1.3,
                            "heatindex_f": 29.6,
                            "dewpoint_c": -3.1,
                            "dewpoint_f": 26.4,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 21.5,
                            "gust_kph": 34.6,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743904800,
                            "time": "2025-04-06 05:00",
                            "temp_c": -1.7,
                            "temp_f": 29.0,
                            "is_day": 0,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/230.png",
                                "code": 1117
                            },
                            "wind_mph": 17.2,
                            "wind_kph": 27.7,
                            "wind_degree": 42,
                            "wind_dir": "NE",
                            "pressure_mb": 1005.0,
                            "pressure_in": 29.68,
                            "precip_mm": 1.54,
                            "precip_in": 0.06,
                            "snow_cm": 0.0,
                            "humidity": 91,
                            "cloud": 100,
                            "feelslike_c": -8.4,
                            "feelslike_f": 16.9,
                            "windchill_c": -8.4,
                            "windchill_f": 16.9,
                            "heatindex_c": -1.7,
                            "heatindex_f": 29.0,
                            "dewpoint_c": -2.9,
                            "dewpoint_f": 26.7,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 93,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 22.5,
                            "gust_kph": 36.3,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743908400,
                            "time": "2025-04-06 06:00",
                            "temp_c": -1.8,
                            "temp_f": 28.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                                "code": 1117
                            },
                            "wind_mph": 17.2,
                            "wind_kph": 27.7,
                            "wind_degree": 44,
                            "wind_dir": "NE",
                            "pressure_mb": 1005.0,
                            "pressure_in": 29.69,
                            "precip_mm": 1.41,
                            "precip_in": 0.06,
                            "snow_cm": 0.0,
                            "humidity": 93,
                            "cloud": 100,
                            "feelslike_c": -8.6,
                            "feelslike_f": 16.5,
                            "windchill_c": -8.6,
                            "windchill_f": 16.5,
                            "heatindex_c": -1.8,
                            "heatindex_f": 28.7,
                            "dewpoint_c": -2.9,
                            "dewpoint_f": 26.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 92,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 23.0,
                            "gust_kph": 37.0,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1743912000,
                            "time": "2025-04-06 07:00",
                            "temp_c": -1.8,
                            "temp_f": 28.8,
                            "is_day": 1,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                                "code": 1117
                            },
                            "wind_mph": 17.7,
                            "wind_kph": 28.4,
                            "wind_degree": 39,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.7,
                            "precip_mm": 1.67,
                            "precip_in": 0.07,
                            "snow_cm": 0.0,
                            "humidity": 94,
                            "cloud": 100,
                            "feelslike_c": -8.6,
                            "feelslike_f": 16.5,
                            "windchill_c": -8.6,
                            "windchill_f": 16.5,
                            "heatindex_c": -1.8,
                            "heatindex_f": 28.8,
                            "dewpoint_c": -2.6,
                            "dewpoint_f": 27.3,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 92,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 23.6,
                            "gust_kph": 38.0,
                            "uv": 0.1
                        },
                        {
                            "time_epoch": 1743915600,
                            "time": "2025-04-06 08:00",
                            "temp_c": -1.7,
                            "temp_f": 28.9,
                            "is_day": 1,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                                "code": 1117
                            },
                            "wind_mph": 17.7,
                            "wind_kph": 28.4,
                            "wind_degree": 37,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.7,
                            "precip_mm": 1.96,
                            "precip_in": 0.08,
                            "snow_cm": 0.0,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -8.6,
                            "feelslike_f": 16.6,
                            "windchill_c": -8.6,
                            "windchill_f": 16.6,
                            "heatindex_c": -1.7,
                            "heatindex_f": 28.9,
                            "dewpoint_c": -2.5,
                            "dewpoint_f": 27.5,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 92,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 23.8,
                            "gust_kph": 38.3,
                            "uv": 0.2
                        },
                        {
                            "time_epoch": 1743919200,
                            "time": "2025-04-06 09:00",
                            "temp_c": -1.6,
                            "temp_f": 29.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                                "code": 1117
                            },
                            "wind_mph": 18.3,
                            "wind_kph": 29.5,
                            "wind_degree": 40,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.69,
                            "precip_mm": 1.9,
                            "precip_in": 0.07,
                            "snow_cm": 0.0,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -8.6,
                            "feelslike_f": 16.6,
                            "windchill_c": -8.6,
                            "windchill_f": 16.6,
                            "heatindex_c": -1.6,
                            "heatindex_f": 29.1,
                            "dewpoint_c": -2.4,
                            "dewpoint_f": 27.7,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 91,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 24.4,
                            "gust_kph": 39.2,
                            "uv": 0.5
                        },
                        {
                            "time_epoch": 1743922800,
                            "time": "2025-04-06 10:00",
                            "temp_c": -1.5,
                            "temp_f": 29.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                                "code": 1117
                            },
                            "wind_mph": 19.0,
                            "wind_kph": 30.6,
                            "wind_degree": 43,
                            "wind_dir": "NE",
                            "pressure_mb": 1005.0,
                            "pressure_in": 29.69,
                            "precip_mm": 1.65,
                            "precip_in": 0.07,
                            "snow_cm": 0.0,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -8.5,
                            "feelslike_f": 16.7,
                            "windchill_c": -8.5,
                            "windchill_f": 16.7,
                            "heatindex_c": -1.5,
                            "heatindex_f": 29.3,
                            "dewpoint_c": -2.3,
                            "dewpoint_f": 28.0,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 91,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 25.4,
                            "gust_kph": 40.9,
                            "uv": 0.9
                        },
                        {
                            "time_epoch": 1743926400,
                            "time": "2025-04-06 11:00",
                            "temp_c": -1.6,
                            "temp_f": 29.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                                "code": 1117
                            },
                            "wind_mph": 18.6,
                            "wind_kph": 29.9,
                            "wind_degree": 40,
                            "wind_dir": "NE",
                            "pressure_mb": 1005.0,
                            "pressure_in": 29.68,
                            "precip_mm": 1.45,
                            "precip_in": 0.06,
                            "snow_cm": 0.0,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -8.6,
                            "feelslike_f": 16.6,
                            "windchill_c": -8.6,
                            "windchill_f": 16.6,
                            "heatindex_c": -1.6,
                            "heatindex_f": 29.1,
                            "dewpoint_c": -2.3,
                            "dewpoint_f": 27.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 91,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 25.1,
                            "gust_kph": 40.5,
                            "uv": 1.1
                        },
                        {
                            "time_epoch": 1743930000,
                            "time": "2025-04-06 12:00",
                            "temp_c": -1.9,
                            "temp_f": 28.7,
                            "is_day": 1,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                                "code": 1117
                            },
                            "wind_mph": 18.6,
                            "wind_kph": 29.9,
                            "wind_degree": 41,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.7,
                            "precip_mm": 2.74,
                            "precip_in": 0.11,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -8.9,
                            "feelslike_f": 16.0,
                            "windchill_c": -8.9,
                            "windchill_f": 16.0,
                            "heatindex_c": -1.9,
                            "heatindex_f": 28.7,
                            "dewpoint_c": -2.4,
                            "dewpoint_f": 27.7,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 90,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 26.1,
                            "gust_kph": 42.0,
                            "uv": 1.3
                        },
                        {
                            "time_epoch": 1743933600,
                            "time": "2025-04-06 13:00",
                            "temp_c": -1.6,
                            "temp_f": 29.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                                "code": 1117
                            },
                            "wind_mph": 18.1,
                            "wind_kph": 29.2,
                            "wind_degree": 39,
                            "wind_dir": "NE",
                            "pressure_mb": 1007.0,
                            "pressure_in": 29.73,
                            "precip_mm": 1.85,
                            "precip_in": 0.07,
                            "snow_cm": 0.0,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -8.5,
                            "feelslike_f": 16.7,
                            "windchill_c": -8.5,
                            "windchill_f": 16.7,
                            "heatindex_c": -1.6,
                            "heatindex_f": 29.1,
                            "dewpoint_c": -2.2,
                            "dewpoint_f": 28.1,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 90,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 24.9,
                            "gust_kph": 40.0,
                            "uv": 1.4
                        },
                        {
                            "time_epoch": 1743937200,
                            "time": "2025-04-06 14:00",
                            "temp_c": -1.6,
                            "temp_f": 29.1,
                            "is_day": 1,
                            "condition": {
                                "text": "Heavy snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
                                "code": 1225
                            },
                            "wind_mph": 16.8,
                            "wind_kph": 27.0,
                            "wind_degree": 42,
                            "wind_dir": "NE",
                            "pressure_mb": 1007.0,
                            "pressure_in": 29.73,
                            "precip_mm": 0.57,
                            "precip_in": 0.02,
                            "snow_cm": 0.41,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -8.2,
                            "feelslike_f": 17.2,
                            "windchill_c": -8.2,
                            "windchill_f": 17.2,
                            "heatindex_c": -1.6,
                            "heatindex_f": 29.1,
                            "dewpoint_c": -2.4,
                            "dewpoint_f": 27.8,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 22.8,
                            "gust_kph": 36.8,
                            "uv": 1.3
                        },
                        {
                            "time_epoch": 1743940800,
                            "time": "2025-04-06 15:00",
                            "temp_c": -1.9,
                            "temp_f": 28.6,
                            "is_day": 1,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                                "code": 1117
                            },
                            "wind_mph": 17.9,
                            "wind_kph": 28.8,
                            "wind_degree": 43,
                            "wind_dir": "NE",
                            "pressure_mb": 1006.0,
                            "pressure_in": 29.72,
                            "precip_mm": 1.45,
                            "precip_in": 0.06,
                            "snow_cm": 0.0,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -8.8,
                            "feelslike_f": 16.1,
                            "windchill_c": -8.8,
                            "windchill_f": 16.1,
                            "heatindex_c": -1.9,
                            "heatindex_f": 28.6,
                            "dewpoint_c": -2.6,
                            "dewpoint_f": 27.4,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 89,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 24.9,
                            "gust_kph": 40.1,
                            "uv": 0.9
                        },
                        {
                            "time_epoch": 1743944400,
                            "time": "2025-04-06 16:00",
                            "temp_c": -2.1,
                            "temp_f": 28.3,
                            "is_day": 1,
                            "condition": {
                                "text": "Heavy snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
                                "code": 1225
                            },
                            "wind_mph": 16.8,
                            "wind_kph": 27.0,
                            "wind_degree": 41,
                            "wind_dir": "NE",
                            "pressure_mb": 1007.0,
                            "pressure_in": 29.74,
                            "precip_mm": 1.5,
                            "precip_in": 0.06,
                            "snow_cm": 1.09,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -8.8,
                            "feelslike_f": 16.1,
                            "windchill_c": -8.8,
                            "windchill_f": 16.1,
                            "heatindex_c": -2.1,
                            "heatindex_f": 28.3,
                            "dewpoint_c": -2.7,
                            "dewpoint_f": 27.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 23.9,
                            "gust_kph": 38.5,
                            "uv": 0.6
                        },
                        {
                            "time_epoch": 1743948000,
                            "time": "2025-04-06 17:00",
                            "temp_c": -2.5,
                            "temp_f": 27.6,
                            "is_day": 1,
                            "condition": {
                                "text": "Blizzard",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/230.png",
                                "code": 1117
                            },
                            "wind_mph": 17.4,
                            "wind_kph": 28.1,
                            "wind_degree": 42,
                            "wind_dir": "NE",
                            "pressure_mb": 1007.0,
                            "pressure_in": 29.73,
                            "precip_mm": 0.76,
                            "precip_in": 0.03,
                            "snow_cm": 0.0,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -9.5,
                            "feelslike_f": 15.0,
                            "windchill_c": -9.5,
                            "windchill_f": 15.0,
                            "heatindex_c": -2.5,
                            "heatindex_f": 27.6,
                            "dewpoint_c": -3.2,
                            "dewpoint_f": 26.3,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 89,
                            "vis_km": 0.0,
                            "vis_miles": 0.0,
                            "gust_mph": 25.6,
                            "gust_kph": 41.2,
                            "uv": 0.3
                        },
                        {
                            "time_epoch": 1743951600,
                            "time": "2025-04-06 18:00",
                            "temp_c": -2.5,
                            "temp_f": 27.4,
                            "is_day": 1,
                            "condition": {
                                "text": "Heavy snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
                                "code": 1225
                            },
                            "wind_mph": 16.1,
                            "wind_kph": 25.9,
                            "wind_degree": 39,
                            "wind_dir": "NE",
                            "pressure_mb": 1007.0,
                            "pressure_in": 29.75,
                            "precip_mm": 1.5,
                            "precip_in": 0.06,
                            "snow_cm": 1.09,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -9.3,
                            "feelslike_f": 15.3,
                            "windchill_c": -9.3,
                            "windchill_f": 15.3,
                            "heatindex_c": -2.5,
                            "heatindex_f": 27.4,
                            "dewpoint_c": -3.1,
                            "dewpoint_f": 26.3,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 23.8,
                            "gust_kph": 38.2,
                            "uv": 0.1
                        },
                        {
                            "time_epoch": 1743955200,
                            "time": "2025-04-06 19:00",
                            "temp_c": -2.8,
                            "temp_f": 27.0,
                            "is_day": 1,
                            "condition": {
                                "text": "Heavy snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/day/338.png",
                                "code": 1225
                            },
                            "wind_mph": 15.7,
                            "wind_kph": 25.2,
                            "wind_degree": 40,
                            "wind_dir": "NE",
                            "pressure_mb": 1008.0,
                            "pressure_in": 29.75,
                            "precip_mm": 1.54,
                            "precip_in": 0.06,
                            "snow_cm": 1.11,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -9.5,
                            "feelslike_f": 14.9,
                            "windchill_c": -9.5,
                            "windchill_f": 14.9,
                            "heatindex_c": -2.8,
                            "heatindex_f": 27.0,
                            "dewpoint_c": -3.4,
                            "dewpoint_f": 25.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 23.4,
                            "gust_kph": 37.7,
                            "uv": 0.0
                        },
                        {
                            "time_epoch": 1743958800,
                            "time": "2025-04-06 20:00",
                            "temp_c": -2.9,
                            "temp_f": 26.9,
                            "is_day": 0,
                            "condition": {
                                "text": "Heavy snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                                "code": 1225
                            },
                            "wind_mph": 16.3,
                            "wind_kph": 26.3,
                            "wind_degree": 43,
                            "wind_dir": "NE",
                            "pressure_mb": 1008.0,
                            "pressure_in": 29.76,
                            "precip_mm": 1.5,
                            "precip_in": 0.06,
                            "snow_cm": 1.08,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -9.7,
                            "feelslike_f": 14.5,
                            "windchill_c": -9.7,
                            "windchill_f": 14.5,
                            "heatindex_c": -2.9,
                            "heatindex_f": 26.9,
                            "dewpoint_c": -3.5,
                            "dewpoint_f": 25.8,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 24.1,
                            "gust_kph": 38.8,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743962400,
                            "time": "2025-04-06 21:00",
                            "temp_c": -3.1,
                            "temp_f": 26.5,
                            "is_day": 0,
                            "condition": {
                                "text": "Heavy snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                                "code": 1225
                            },
                            "wind_mph": 15.9,
                            "wind_kph": 25.6,
                            "wind_degree": 39,
                            "wind_dir": "NE",
                            "pressure_mb": 1007.0,
                            "pressure_in": 29.75,
                            "precip_mm": 0.66,
                            "precip_in": 0.03,
                            "snow_cm": 0.48,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -9.9,
                            "feelslike_f": 14.1,
                            "windchill_c": -9.9,
                            "windchill_f": 14.1,
                            "heatindex_c": -3.1,
                            "heatindex_f": 26.5,
                            "dewpoint_c": -3.8,
                            "dewpoint_f": 25.2,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 23.7,
                            "gust_kph": 38.2,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743966000,
                            "time": "2025-04-06 22:00",
                            "temp_c": -3.2,
                            "temp_f": 26.2,
                            "is_day": 0,
                            "condition": {
                                "text": "Heavy snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                                "code": 1225
                            },
                            "wind_mph": 15.7,
                            "wind_kph": 25.2,
                            "wind_degree": 40,
                            "wind_dir": "NE",
                            "pressure_mb": 1007.0,
                            "pressure_in": 29.75,
                            "precip_mm": 1.33,
                            "precip_in": 0.05,
                            "snow_cm": 0.96,
                            "humidity": 96,
                            "cloud": 100,
                            "feelslike_c": -10.1,
                            "feelslike_f": 13.8,
                            "windchill_c": -10.1,
                            "windchill_f": 13.8,
                            "heatindex_c": -3.3,
                            "heatindex_f": 26.2,
                            "dewpoint_c": -3.9,
                            "dewpoint_f": 25.1,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 23.2,
                            "gust_kph": 37.3,
                            "uv": 0
                        },
                        {
                            "time_epoch": 1743969600,
                            "time": "2025-04-06 23:00",
                            "temp_c": -3.3,
                            "temp_f": 26.1,
                            "is_day": 0,
                            "condition": {
                                "text": "Heavy snow",
                                "icon": "//cdn.weatherapi.com/weather/64x64/night/338.png",
                                "code": 1225
                            },
                            "wind_mph": 15.9,
                            "wind_kph": 25.6,
                            "wind_degree": 42,
                            "wind_dir": "NE",
                            "pressure_mb": 1007.0,
                            "pressure_in": 29.74,
                            "precip_mm": 0.94,
                            "precip_in": 0.04,
                            "snow_cm": 0.68,
                            "humidity": 95,
                            "cloud": 100,
                            "feelslike_c": -10.2,
                            "feelslike_f": 13.6,
                            "windchill_c": -10.2,
                            "windchill_f": 13.6,
                            "heatindex_c": -3.3,
                            "heatindex_f": 26.1,
                            "dewpoint_c": -4.0,
                            "dewpoint_f": 24.9,
                            "will_it_rain": 1,
                            "chance_of_rain": 100,
                            "will_it_snow": 1,
                            "chance_of_snow": 100,
                            "vis_km": 2.0,
                            "vis_miles": 1.0,
                            "gust_mph": 23.4,
                            "gust_kph": 37.7,
                            "uv": 0
                        }
                    ]
                }
            ]
        },
        "alerts": {
            "alert": [
                {
                    "headline": "Снег",
                    "msgtype": "Alert",
                    "severity": "Moderate",
                    "urgency": "Immediate",
                    "areas": "",
                    "category": "Met",
                    "certainty": "Likely",
                    "event": "Снег",
                    "note": "",
                    "effective": "2025-04-05T08:21:00-00:00",
                    "expires": "2025-04-07T20:00:00-00:00",
                    "desc": "В связи с влиянием активного циклона и его атмосферных фронтов, в период с 02 часов 06 апреля до 09 часов 07 апреля в Москве ожидается снег, местами сильный, метель. 07 апреля с 09 часов до 23 часов ожидается снег, мокрый снег, налипание мокрого снега на проводах и деревьях, а также установление временного снежного покрова.",
                    "instruction": ""
                },
                {
                    "headline": "Ветер",
                    "msgtype": "Alert",
                    "severity": "Moderate",
                    "urgency": "Immediate",
                    "areas": "",
                    "category": "Met",
                    "certainty": "Likely",
                    "event": "Ветер",
                    "note": "",
                    "effective": "2025-04-05T08:21:00-00:00",
                    "expires": "2025-04-07T20:00:00-00:00",
                    "desc": "06 и 07 апреля местами усиление северо-восточного ветра с порывами до 15 м/с.",
                    "instruction": ""
                },
                {
                    "headline": "Снег",
                    "msgtype": "Update",
                    "severity": "Moderate",
                    "urgency": "Immediate",
                    "areas": "",
                    "category": "Met",
                    "certainty": "Likely",
                    "event": "Снег",
                    "note": "",
                    "effective": "2025-04-05T08:22:00-00:00",
                    "expires": "2025-04-07T20:00:00-00:00",
                    "desc": "В связи с влиянием активного циклона и его атмосферных фронтов, в период с 01 часа 06 апреля до 23 часов 07 апреля ожидаются осадки, местами сильные (снег, мокрый снег). В отдельных районах налипание мокрого снега на проводах и деревьях, гололёд, гололедица на дорогах, в большинстве районов области установление временного снежного покрова.",
                    "instruction": ""
                },
                {
                    "headline": "Снег",
                    "msgtype": "Update",
                    "severity": "Moderate",
                    "urgency": "Immediate",
                    "areas": "",
                    "category": "Met",
                    "certainty": "Likely",
                    "event": "Снег",
                    "note": "",
                    "effective": "2025-04-05T08:23:00-00:00",
                    "expires": "2025-04-07T20:00:00-00:00",
                    "desc": "В связи с влиянием активного циклона и его атмосферных фронтов, в период с 01 часа 06 апреля до 23 часов 07 апреля ожидаются осадки, местами сильные (снег, мокрый снег). В отдельных районах налипание мокрого снега на проводах и деревьях, гололёд, гололедица на дорогах, в большинстве районов области установление временного снежного покрова.",
                    "instruction": ""
                },
                {
                    "headline": "Снег",
                    "msgtype": "Alert",
                    "severity": "Moderate",
                    "urgency": "Immediate",
                    "areas": "",
                    "category": "Met",
                    "certainty": "Likely",
                    "event": "Снег",
                    "note": "",
                    "effective": "2025-04-05T08:23:00-00:00",
                    "expires": "2025-04-07T20:00:00-00:00",
                    "desc": "В связи с влиянием активного циклона и его атмосферных фронтов, в период с 02 часов 06 апреля до 09 часов 07 апреля в Москве ожидается снег, местами сильный, метель. 07 апреля с 09 часов до 23 часов ожидается снег, мокрый снег, налипание мокрого снега на проводах и деревьях. В течение указанных периодов гололедица на дорогах, установление временного снежного покрова.",
                    "instruction": ""
                }
            ]
        }
    }
""".trimIndent()